"""add voice tables

Revision ID: ba884be8f077
Revises: dc54b25d8b6c
Create Date: 2026-02-06 00:00:00.000000

"""
import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, FernetBackend, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # pyright: ignore  # noqa: F401
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence  # pyright: ignore

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID # pyright: ignore
sa.DateTimeUTC = DateTimeUTC  # pyright: ignore
sa.ORA_JSONB = ORA_JSONB  # pyright: ignore
sa.EncryptedString = EncryptedString  # pyright: ignore
sa.EncryptedText = EncryptedText  # pyright: ignore
sa.StoredObject = StoredObject  # pyright: ignore
sa.PasswordHash = PasswordHash  # pyright: ignore

# revision identifiers, used by Alembic.
revision = 'ba884be8f077'
down_revision = 'dc54b25d8b6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_number',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('number_type', sa.String(length=20), nullable=False),
    sa.Column('caller_id_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_phone_number_team_id_team'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_phone_number_user_id_user_account'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_number')),
    sa.UniqueConstraint('number', name=op.f('uq_phone_number_number')),
    comment='Phone numbers assigned to users'
    )
    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_number_number'), ['number'], unique=True)

    op.create_table('extension',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('extension_number', sa.String(length=10), nullable=False),
    sa.Column('phone_number_id', sa.GUID(length=16), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_number.id'], name=op.f('fk_extension_phone_number_id_phone_number'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_extension_user_id_user_account'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extension')),
    sa.UniqueConstraint('extension_number', name=op.f('uq_extension_extension_number')),
    comment='Internal phone extensions'
    )
    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extension_extension_number'), ['extension_number'], unique=True)

    op.create_table('voicemail_box',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('extension_id', sa.GUID(length=16), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('pin', sa.EncryptedString(key='secret-key', backend=FernetBackend, length=None), nullable=True),
    sa.Column('greeting_type', sa.String(length=20), nullable=False),
    sa.Column('greeting_file_path', sa.String(length=500), nullable=True),
    sa.Column('max_message_length_seconds', sa.Integer(), nullable=False),
    sa.Column('email_notification', sa.Boolean(), nullable=False),
    sa.Column('email_attach_audio', sa.Boolean(), nullable=False),
    sa.Column('transcription_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_delete_days', sa.Integer(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extension_id'], ['extension.id'], name=op.f('fk_voicemail_box_extension_id_extension'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voicemail_box')),
    sa.UniqueConstraint('extension_id', name=op.f('uq_voicemail_box_extension_id')),
    comment='Voicemail box configuration per extension'
    )

    op.create_table('voicemail_message',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('voicemail_box_id', sa.GUID(length=16), nullable=False),
    sa.Column('caller_number', sa.String(length=20), nullable=False),
    sa.Column('caller_name', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('audio_file_path', sa.String(length=500), nullable=False),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['voicemail_box_id'], ['voicemail_box.id'], name=op.f('fk_voicemail_message_voicemail_box_id_voicemail_box'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voicemail_message')),
    comment='Individual voicemail messages'
    )
    with op.batch_alter_table('voicemail_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voicemail_message_voicemail_box_id'), ['voicemail_box_id'], unique=False)

    op.create_table('forwarding_rule',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('extension_id', sa.GUID(length=16), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('destination_type', sa.String(length=20), nullable=False),
    sa.Column('destination_value', sa.String(length=100), nullable=False),
    sa.Column('ring_timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extension_id'], ['extension.id'], name=op.f('fk_forwarding_rule_extension_id_extension'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forwarding_rule')),
    comment='Call forwarding rules per extension'
    )
    with op.batch_alter_table('forwarding_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forwarding_rule_extension_id'), ['extension_id'], unique=False)

    op.create_table('do_not_disturb',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('extension_id', sa.GUID(length=16), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('schedule_start', sa.Time(), nullable=True),
    sa.Column('schedule_end', sa.Time(), nullable=True),
    sa.Column('schedule_days', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('allow_list', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extension_id'], ['extension.id'], name=op.f('fk_do_not_disturb_extension_id_extension'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_do_not_disturb')),
    sa.UniqueConstraint('extension_id', name=op.f('uq_do_not_disturb_extension_id')),
    comment='Do Not Disturb settings per extension'
    )
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('do_not_disturb')
    with op.batch_alter_table('forwarding_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forwarding_rule_extension_id'))

    op.drop_table('forwarding_rule')
    with op.batch_alter_table('voicemail_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voicemail_message_voicemail_box_id'))

    op.drop_table('voicemail_message')
    op.drop_table('voicemail_box')
    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extension_extension_number'))

    op.drop_table('extension')
    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_number_number'))

    op.drop_table('phone_number')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
