"""add device tables

Revision ID: b1cf87cc0066
Revises: dc54b25d8b6c
Create Date: 2026-02-08 03:58:49.084828

"""
import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # pyright: ignore  # noqa: F401
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence  # pyright: ignore

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID # pyright: ignore
sa.DateTimeUTC = DateTimeUTC  # pyright: ignore
sa.ORA_JSONB = ORA_JSONB  # pyright: ignore
sa.EncryptedString = EncryptedString  # pyright: ignore
sa.EncryptedText = EncryptedText  # pyright: ignore
sa.StoredObject = StoredObject  # pyright: ignore
sa.PasswordHash = PasswordHash  # pyright: ignore

# revision identifiers, used by Alembic.
revision = 'b1cf87cc0066'
down_revision = 'dc54b25d8b6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('sip_username', sa.String(length=100), nullable=False),
    sa.Column('sip_server', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('provisioned_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_device_team_id_team'), ondelete='set null'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_device_user_id_user_account'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device')),
    comment='Devices registered to user accounts'
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_device_type'), ['device_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_user_id'), ['user_id'], unique=False)

    op.create_table('device_line_assignment',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('device_id', sa.GUID(length=16), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('extension_id', sa.GUID(length=16), nullable=True),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('line_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_device_line_assignment_device_id_device'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_line_assignment')),
    sa.UniqueConstraint('device_id', 'line_number', name=op.f('uq_device_line_assignment_device_id')),
    comment='Line key assignments for devices'
    )
    with op.batch_alter_table('device_line_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_line_assignment_device_id'), ['device_id'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_line_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_line_assignment_device_id'))

    op.drop_table('device_line_assignment')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_user_id'))
        batch_op.drop_index(batch_op.f('ix_device_team_id'))
        batch_op.drop_index(batch_op.f('ix_device_status'))
        batch_op.drop_index(batch_op.f('ix_device_name'))
        batch_op.drop_index(batch_op.f('ix_device_device_type'))

    op.drop_table('device')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
