"""

Revision ID: cab4c48aa481
Revises: a1b2c3d4e5f6
Create Date: 2026-04-28 16:53:49.734778

"""
import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # pyright: ignore  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence  # pyright: ignore

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID # pyright: ignore
sa.DateTimeUTC = DateTimeUTC  # pyright: ignore
sa.ORA_JSONB = ORA_JSONB  # pyright: ignore
sa.EncryptedString = EncryptedString  # pyright: ignore
sa.EncryptedText = EncryptedText  # pyright: ignore
sa.StoredObject = StoredObject  # pyright: ignore
sa.PasswordHash = PasswordHash  # pyright: ignore

# revision identifiers, used by Alembic.
revision = 'cab4c48aa481'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_extension_extension_number'), type_='unique')

    with op.batch_alter_table('fax_email_route', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fax_email_route_fax_number_id'))

    with op.batch_alter_table('fax_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fax_message_direction'))
        batch_op.drop_index(batch_op.f('ix_fax_message_fax_number_id'))
        batch_op.drop_index(batch_op.f('ix_fax_message_received_at'))
        batch_op.drop_index(batch_op.f('ix_fax_message_status'))

    with op.batch_alter_table('fax_number', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fax_number_team_id'))
        batch_op.drop_index(batch_op.f('ix_fax_number_user_id'))
        batch_op.drop_constraint(batch_op.f('uq_fax_number_number'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_fax_number_number'))
        batch_op.create_index(batch_op.f('ix_fax_number_number'), ['number'], unique=True)

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index('ix_organization_slug_unique', ['slug'], unique=True)

    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_phone_number_number'), type_='unique')

    with op.batch_alter_table('team_role_permission', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_team_role_permission_team_id_role_feature_area'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_team_role_permission_team_id'), ['team_id', 'role', 'feature_area'])

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ticket_ticket_number'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_ticket_ticket_number'))
        batch_op.create_index(batch_op.f('ix_ticket_ticket_number'), ['ticket_number'], unique=True)
        batch_op.create_table_comment(
        'Support tickets for helpdesk system',
        existing_comment=None
    )

    with op.batch_alter_table('ticket_attachment', schema=None) as batch_op:
        batch_op.create_table_comment(
        'File attachments for support ticket messages',
        existing_comment=None
    )

    with op.batch_alter_table('ticket_message', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Messages within support ticket threads',
        existing_comment=None
    )

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_message', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Messages within support ticket threads'
    )

    with op.batch_alter_table('ticket_attachment', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='File attachments for support ticket messages'
    )

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Support tickets for helpdesk system'
    )
        batch_op.drop_index(batch_op.f('ix_ticket_ticket_number'))
        batch_op.create_index(batch_op.f('ix_ticket_ticket_number'), ['ticket_number'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_ticket_ticket_number'), ['ticket_number'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('team_role_permission', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_team_role_permission_team_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_team_role_permission_team_id_role_feature_area'), ['team_id', 'role', 'feature_area'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_phone_number_number'), ['number'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index('ix_organization_slug_unique')

    with op.batch_alter_table('fax_number', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fax_number_number'))
        batch_op.create_index(batch_op.f('ix_fax_number_number'), ['number'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_fax_number_number'), ['number'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_fax_number_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fax_number_team_id'), ['team_id'], unique=False)

    with op.batch_alter_table('fax_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fax_message_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fax_message_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fax_message_fax_number_id'), ['fax_number_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fax_message_direction'), ['direction'], unique=False)

    with op.batch_alter_table('fax_email_route', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fax_email_route_fax_number_id'), ['fax_number_id'], unique=False)

    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_extension_extension_number'), ['extension_number'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
