"""

Revision ID: 158c72763225
Revises: e2f3a4b5c6d7
Create Date: 2026-05-01 16:12:15.370805

"""
import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # pyright: ignore  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence  # pyright: ignore

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID # pyright: ignore
sa.DateTimeUTC = DateTimeUTC  # pyright: ignore
sa.ORA_JSONB = ORA_JSONB  # pyright: ignore
sa.EncryptedString = EncryptedString  # pyright: ignore
sa.EncryptedText = EncryptedText  # pyright: ignore
sa.StoredObject = StoredObject  # pyright: ignore
sa.PasswordHash = PasswordHash  # pyright: ignore

# revision identifiers, used by Alembic.
revision = '158c72763225'
down_revision = 'e2f3a4b5c6d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_delivery',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('webhook_id', sa.GUID(length=16), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhook.id'], name=op.f('fk_webhook_delivery_webhook_id_webhook'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_delivery')),
    comment='Records of individual webhook delivery attempts'
    )
    with op.batch_alter_table('webhook_delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_delivery_webhook_id'), ['webhook_id'], unique=False)

    with op.batch_alter_table('music_on_hold', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_music_on_hold_name'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_music_on_hold_name'))
        batch_op.create_index(batch_op.f('ix_music_on_hold_name'), ['name'], unique=True)

    with op.batch_alter_table('webhook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_webhook_is_active'))

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_is_active'), ['is_active'], unique=False)
        batch_op.drop_column('sa_orm_sentinel')

    with op.batch_alter_table('music_on_hold', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_music_on_hold_name'))
        batch_op.create_index(batch_op.f('ix_music_on_hold_name'), ['name'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_music_on_hold_name'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('sa_orm_sentinel')

    with op.batch_alter_table('webhook_delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_delivery_webhook_id'))

    op.drop_table('webhook_delivery')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
