"""add webhook delivery retry fields

Revision ID: 08ae773b5b5f
Revises: 03c99986d734
Create Date: 2026-05-07 20:58:01.628682

"""
import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # pyright: ignore  # noqa: F401
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence  # pyright: ignore

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID # pyright: ignore
sa.DateTimeUTC = DateTimeUTC  # pyright: ignore
sa.ORA_JSONB = ORA_JSONB  # pyright: ignore
sa.EncryptedString = EncryptedString  # pyright: ignore
sa.EncryptedText = EncryptedText  # pyright: ignore
sa.StoredObject = StoredObject  # pyright: ignore
sa.PasswordHash = PasswordHash  # pyright: ignore

# revision identifiers, used by Alembic.
revision = '08ae773b5b5f'
down_revision = '03c99986d734'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endpoint_id', sa.GUID(length=16), nullable=True))
        batch_op.add_column(sa.Column('endpoint_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('max_retries', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_webhook_delivery_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_delivery_next_retry_at'), ['next_retry_at'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_webhook_delivery_endpoint_id_webhook_endpoint'), 'webhook_endpoint', ['endpoint_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_delivery', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_webhook_delivery_endpoint_id_webhook_endpoint'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_webhook_delivery_next_retry_at'))
        batch_op.drop_index(batch_op.f('ix_webhook_delivery_endpoint_id'))
        batch_op.drop_column('next_retry_at')
        batch_op.drop_column('max_retries')
        batch_op.drop_column('retry_count')
        batch_op.drop_column('payload')
        batch_op.drop_column('endpoint_url')
        batch_op.drop_column('endpoint_id')

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
