"""add fax tables

Revision ID: ee846255bf42
Revises: dc54b25d8b6c
Create Date: 2026-02-06 00:00:00.000000

"""
import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import GUID, DateTimeUTC
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    from collections.abc import Sequence  # pyright: ignore

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID  # pyright: ignore
sa.DateTimeUTC = DateTimeUTC  # pyright: ignore

# revision identifiers, used by Alembic.
revision = 'ee846255bf42'
down_revision = 'dc54b25d8b6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fax_number',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_fax_number_user_id_user_account'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_fax_number_team_id_team'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fax_number')),
    sa.UniqueConstraint('number', name=op.f('uq_fax_number_number')),
    )
    with op.batch_alter_table('fax_number', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fax_number_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_fax_number_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fax_number_team_id'), ['team_id'], unique=False)

    op.create_table('fax_email_route',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('fax_number_id', sa.GUID(length=16), nullable=False),
    sa.Column('email_address', sa.String(length=320), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notify_on_failure', sa.Boolean(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fax_number_id'], ['fax_number.id'], name=op.f('fk_fax_email_route_fax_number_id_fax_number'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fax_email_route')),
    )
    with op.batch_alter_table('fax_email_route', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fax_email_route_fax_number_id'), ['fax_number_id'], unique=False)

    op.create_table('fax_message',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('fax_number_id', sa.GUID(length=16), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('remote_number', sa.String(length=20), nullable=False),
    sa.Column('remote_name', sa.String(length=100), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('delivered_to_emails', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('received_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fax_number_id'], ['fax_number.id'], name=op.f('fk_fax_message_fax_number_id_fax_number'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fax_message')),
    )
    with op.batch_alter_table('fax_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fax_message_fax_number_id'), ['fax_number_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fax_message_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_fax_message_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fax_message_received_at'), ['received_at'], unique=False)
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fax_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fax_message_received_at'))
        batch_op.drop_index(batch_op.f('ix_fax_message_status'))
        batch_op.drop_index(batch_op.f('ix_fax_message_direction'))
        batch_op.drop_index(batch_op.f('ix_fax_message_fax_number_id'))

    op.drop_table('fax_message')
    with op.batch_alter_table('fax_email_route', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fax_email_route_fax_number_id'))

    op.drop_table('fax_email_route')
    with op.batch_alter_table('fax_number', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fax_number_team_id'))
        batch_op.drop_index(batch_op.f('ix_fax_number_user_id'))
        batch_op.drop_index(batch_op.f('ix_fax_number_number'))

    op.drop_table('fax_number')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
