"""add background_task table

Revision ID: ed0e3773330c
Revises: 158c72763225
Create Date: 2026-05-01 17:16:09.898926

"""
import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # pyright: ignore  # noqa: F401
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence  # pyright: ignore

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID # pyright: ignore
sa.DateTimeUTC = DateTimeUTC  # pyright: ignore
sa.ORA_JSONB = ORA_JSONB  # pyright: ignore
sa.EncryptedString = EncryptedString  # pyright: ignore
sa.EncryptedText = EncryptedText  # pyright: ignore
sa.StoredObject = StoredObject  # pyright: ignore
sa.PasswordHash = PasswordHash  # pyright: ignore

# revision identifiers, used by Alembic.
revision = 'ed0e3773330c'
down_revision = '158c72763225'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_task',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.GUID(length=16), nullable=True),
    sa.Column('team_id', sa.GUID(length=16), nullable=False),
    sa.Column('initiated_by_id', sa.GUID(length=16), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('saq_job_key', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['user_account.id'], name=op.f('fk_background_task_initiated_by_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_background_task_team_id_team'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_task')),
    comment='Tracks background job lifecycle and results'
    )
    with op.batch_alter_table('background_task', schema=None) as batch_op:
        batch_op.create_index('ix_background_task_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_task_initiated_by_id'), ['initiated_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_task_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_task_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_task_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_task_team_id'))
        batch_op.drop_index(batch_op.f('ix_background_task_task_type'))
        batch_op.drop_index(batch_op.f('ix_background_task_status'))
        batch_op.drop_index(batch_op.f('ix_background_task_initiated_by_id'))
        batch_op.drop_index('ix_background_task_entity')

    op.drop_table('background_task')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
