"""

Revision ID: d42171b27bd7
Revises: 45bd6a38e9cf
Create Date: 2026-05-12 15:03:37.976028

"""
import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # pyright: ignore  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence  # pyright: ignore

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID # pyright: ignore
sa.DateTimeUTC = DateTimeUTC  # pyright: ignore
sa.ORA_JSONB = ORA_JSONB  # pyright: ignore
sa.EncryptedString = EncryptedString  # pyright: ignore
sa.EncryptedText = EncryptedText  # pyright: ignore
sa.StoredObject = StoredObject  # pyright: ignore
sa.PasswordHash = PasswordHash  # pyright: ignore

# revision identifiers, used by Alembic.
revision = 'd42171b27bd7'
down_revision = '45bd6a38e9cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_line_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_device_line_assignment_device_id'), type_='unique')
        batch_op.create_index(batch_op.f('ix_device_line_assignment_extension_id'), ['extension_id'], unique=False)
        batch_op.create_unique_constraint('uq_device_line_assignment_device_line', ['device_id', 'line_number'])

    with op.batch_alter_table('e911_registration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_e911_registration_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_e911_registration_phone_number_id'), ['phone_number_id'], unique=False)

    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extension_phone_number_id'), ['phone_number_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('fax_email_route', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Fax-to-email delivery routing rules',
        existing_comment=None
    )

    with op.batch_alter_table('fax_message', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Sent and received fax message records',
        existing_comment=None
    )

    with op.batch_alter_table('fax_number', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Fax DIDs assigned to user accounts',
        existing_comment=None
    )

    with op.batch_alter_table('ivr_menu_option', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ivr_menu_option_ivr_menu_id'), type_='unique')
        batch_op.create_unique_constraint('uq_ivr_menu_option_menu_digit', ['ivr_menu_id', 'digit'])

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_slug_unique'))
        batch_op.drop_constraint(batch_op.f('uq_organization_slug'), type_='unique')
        batch_op.create_table_comment(
        'Tenant organization settings and profile',
        existing_comment=None
    )

    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_number_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_slug_unique'))
        batch_op.drop_constraint(batch_op.f('uq_role_slug'), type_='unique')
        batch_op.create_table_comment(
        'Application roles for access control',
        existing_comment=None
    )

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_slug_unique'))
        batch_op.drop_constraint(batch_op.f('uq_tag_slug'), type_='unique')
        batch_op.create_table_comment(
        'Tags for organizing and categorizing resources',
        existing_comment=None
    )

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_slug_unique'))
        batch_op.drop_constraint(batch_op.f('uq_team_slug'), type_='unique')
        batch_op.create_table_comment(
        'Teams of users with shared permissions and resources',
        existing_comment=None
    )

    with op.batch_alter_table('team_invitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_invitation_invited_by_id'), ['invited_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invitation_team_id'), ['team_id'], unique=False)
        batch_op.create_table_comment(
        'Pending team membership invitations',
        existing_comment=None
    )

    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_team_member_user_id'), type_='unique')
        batch_op.create_index(batch_op.f('ix_team_member_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_member_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_team_member_user_team', ['user_id', 'team_id'])
        batch_op.create_table_comment(
        'Team membership records',
        existing_comment=None
    )

    with op.batch_alter_table('team_role_permission', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_team_role_permission_team_id'), type_='unique')
        batch_op.create_unique_constraint('uq_team_role_permission_team_role_feature', ['team_id', 'role', 'feature_area'])
        batch_op.create_table_comment(
        'Per-role permission grants scoped by team and feature area',
        existing_comment=None
    )

    with op.batch_alter_table('ticket_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_attachment_uploaded_by_id'), ['uploaded_by_id'], unique=False)

    with op.batch_alter_table('user_account_oauth', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_account_oauth_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account_oauth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_account_oauth_user_id'))

    with op.batch_alter_table('ticket_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_attachment_uploaded_by_id'))

    with op.batch_alter_table('team_role_permission', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Per-role permission grants scoped by team and feature area'
    )
        batch_op.drop_constraint('uq_team_role_permission_team_role_feature', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_team_role_permission_team_id'), ['team_id', 'role', 'feature_area'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Team membership records'
    )
        batch_op.drop_constraint('uq_team_member_user_team', type_='unique')
        batch_op.drop_index(batch_op.f('ix_team_member_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_member_team_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_team_member_user_id'), ['user_id', 'team_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('team_invitation', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Pending team membership invitations'
    )
        batch_op.drop_index(batch_op.f('ix_team_invitation_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_invitation_invited_by_id'))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Teams of users with shared permissions and resources'
    )
        batch_op.create_unique_constraint(batch_op.f('uq_team_slug'), ['slug'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_team_slug_unique'), ['slug'], unique=True)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Tags for organizing and categorizing resources'
    )
        batch_op.create_unique_constraint(batch_op.f('uq_tag_slug'), ['slug'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_tag_slug_unique'), ['slug'], unique=True)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Application roles for access control'
    )
        batch_op.create_unique_constraint(batch_op.f('uq_role_slug'), ['slug'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_role_slug_unique'), ['slug'], unique=True)

    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_number_user_id'))

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Tenant organization settings and profile'
    )
        batch_op.create_unique_constraint(batch_op.f('uq_organization_slug'), ['slug'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_organization_slug_unique'), ['slug'], unique=True)

    with op.batch_alter_table('ivr_menu_option', schema=None) as batch_op:
        batch_op.drop_constraint('uq_ivr_menu_option_menu_digit', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_ivr_menu_option_ivr_menu_id'), ['ivr_menu_id', 'digit'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('fax_number', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Fax DIDs assigned to user accounts'
    )

    with op.batch_alter_table('fax_message', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Sent and received fax message records'
    )

    with op.batch_alter_table('fax_email_route', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Fax-to-email delivery routing rules'
    )

    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extension_user_id'))
        batch_op.drop_index(batch_op.f('ix_extension_phone_number_id'))

    with op.batch_alter_table('e911_registration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_e911_registration_phone_number_id'))
        batch_op.drop_index(batch_op.f('ix_e911_registration_location_id'))

    with op.batch_alter_table('device_line_assignment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_device_line_assignment_device_line', type_='unique')
        batch_op.drop_index(batch_op.f('ix_device_line_assignment_extension_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_device_line_assignment_device_id'), ['device_id', 'line_number'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
