"""add device location/connection FKs and line assignment extension FK

Revision ID: c50165c5648a
Revises: ed0e3773330c
Create Date: 2026-05-01 17:48:35.185773

"""
import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # pyright: ignore  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence  # pyright: ignore

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID # pyright: ignore
sa.DateTimeUTC = DateTimeUTC  # pyright: ignore
sa.ORA_JSONB = ORA_JSONB  # pyright: ignore
sa.EncryptedString = EncryptedString  # pyright: ignore
sa.EncryptedText = EncryptedText  # pyright: ignore
sa.StoredObject = StoredObject  # pyright: ignore
sa.PasswordHash = PasswordHash  # pyright: ignore

# revision identifiers, used by Alembic.
revision = 'c50165c5648a'
down_revision = 'ed0e3773330c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.GUID(length=16), nullable=True))
        batch_op.add_column(sa.Column('connection_id', sa.GUID(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_device_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_location_id'), ['location_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_device_location_id_location'), 'location', ['location_id'], ['id'], ondelete='set null')
        batch_op.create_foreign_key(batch_op.f('fk_device_connection_id_connection'), 'connection', ['connection_id'], ['id'], ondelete='set null')

    with op.batch_alter_table('device_line_assignment', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_device_line_assignment_extension_id_extension'), 'extension', ['extension_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_line_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_device_line_assignment_extension_id_extension'), type_='foreignkey')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_device_connection_id_connection'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_device_location_id_location'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_device_location_id'))
        batch_op.drop_index(batch_op.f('ix_device_connection_id'))
        batch_op.drop_column('connection_id')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
