"""add index on phone_number.team_id

Revision ID: 45bd6a38e9cf
Revises: 100edd8b4efd
Create Date: 2026-05-08 05:39:35.350740

"""
import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # pyright: ignore  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence  # pyright: ignore

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID # pyright: ignore
sa.DateTimeUTC = DateTimeUTC  # pyright: ignore
sa.ORA_JSONB = ORA_JSONB  # pyright: ignore
sa.EncryptedString = EncryptedString  # pyright: ignore
sa.EncryptedText = EncryptedText  # pyright: ignore
sa.StoredObject = StoredObject  # pyright: ignore
sa.PasswordHash = PasswordHash  # pyright: ignore

# revision identifiers, used by Alembic.
revision = '45bd6a38e9cf'
down_revision = '100edd8b4efd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fax_email_route', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fax_email_route_fax_number_id'), ['fax_number_id'], unique=False)

    with op.batch_alter_table('fax_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fax_message_fax_number_id'), ['fax_number_id'], unique=False)

    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_number_team_id'), ['team_id'], unique=False)

    with op.batch_alter_table('user_account_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_account_role_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_account_role_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_account_role_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_account_role_role_id'))

    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_number_team_id'))

    with op.batch_alter_table('fax_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fax_message_fax_number_id'))

    with op.batch_alter_table('fax_email_route', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fax_email_route_fax_number_id'))

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
