"""add support tickets

Revision ID: a424720f5029
Revises: dc54b25d8b6c
Create Date: 2026-02-06 00:00:00.000000

"""
import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import GUID, DateTimeUTC

if TYPE_CHECKING:
    from collections.abc import Sequence  # pyright: ignore

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID  # pyright: ignore
sa.DateTimeUTC = DateTimeUTC  # pyright: ignore

# revision identifiers, used by Alembic.
revision = 'a424720f5029'
down_revision = 'dc54b25d8b6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('assigned_to_id', sa.GUID(length=16), nullable=True),
    sa.Column('team_id', sa.GUID(length=16), nullable=True),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_read_by_user', sa.Boolean(), nullable=False),
    sa.Column('is_read_by_agent', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_ticket_user_id_user_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user_account.id'], name=op.f('fk_ticket_assigned_to_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_ticket_team_id_team'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket')),
    sa.UniqueConstraint('ticket_number', name=op.f('uq_ticket_ticket_number')),
    comment='Support tickets for helpdesk system'
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_ticket_number'), ['ticket_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_ticket_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_priority'), ['priority'], unique=False)

    op.create_table('ticket_message',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('ticket_id', sa.GUID(length=16), nullable=False),
    sa.Column('author_id', sa.GUID(length=16), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('is_internal_note', sa.Boolean(), nullable=False),
    sa.Column('is_system_message', sa.Boolean(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], name=op.f('fk_ticket_message_ticket_id_ticket'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['user_account.id'], name=op.f('fk_ticket_message_author_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_message')),
    comment='Messages within support ticket threads'
    )
    with op.batch_alter_table('ticket_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_message_ticket_id'), ['ticket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_message_author_id'), ['author_id'], unique=False)

    op.create_table('ticket_attachment',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('ticket_message_id', sa.GUID(length=16), nullable=False),
    sa.Column('ticket_id', sa.GUID(length=16), nullable=False),
    sa.Column('uploaded_by_id', sa.GUID(length=16), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('is_inline', sa.Boolean(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_message_id'], ['ticket_message.id'], name=op.f('fk_ticket_attachment_ticket_message_id_ticket_message'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], name=op.f('fk_ticket_attachment_ticket_id_ticket'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user_account.id'], name=op.f('fk_ticket_attachment_uploaded_by_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_attachment')),
    comment='File attachments for support ticket messages'
    )
    with op.batch_alter_table('ticket_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_attachment_ticket_message_id'), ['ticket_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_attachment_ticket_id'), ['ticket_id'], unique=False)
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_attachment_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_attachment_ticket_message_id'))

    op.drop_table('ticket_attachment')

    with op.batch_alter_table('ticket_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_message_author_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_message_ticket_id'))

    op.drop_table('ticket_message')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_priority'))
        batch_op.drop_index(batch_op.f('ix_ticket_status'))
        batch_op.drop_index(batch_op.f('ix_ticket_ticket_number'))
        batch_op.drop_index(batch_op.f('ix_ticket_team_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_assigned_to_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_user_id'))

    op.drop_table('ticket')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
