import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { toast } from "sonner"
import { useAuthStore } from "@/lib/auth"
import { client } from "@/lib/generated/api/client.gen"

/**
 * Per-upload size limit (mirrored from the server).
 */
export const MAX_UPLOAD_SIZE_BYTES = 25 * 1024 * 1024

/**
 * Allowed values for the `?purpose=` query string on `POST /api/uploads`.
 */
export type AttachmentPurpose = "attachment" | "avatar" | "team_logo" | "import" | "other"

/**
 * Shape of the Attachment payload returned by the uploads API.
 *
 * Defined here (instead of relying on the generated client) because the
 * generated client is regenerated by `make types` against an OpenAPI schema
 * that may lag behind backend changes. The fields mirror the server-side
 * response struct.
 */
export interface Attachment {
  id: string
  originalFilename: string
  contentType: string
  sizeBytes: number
  purpose: AttachmentPurpose
  uploadedById: string
  teamId: string | null
  checksumSha256: string
  createdAt: string
  updatedAt: string
  /** Relative path, e.g. `/api/uploads/{id}/content`. */
  downloadUrl?: string
}

export interface AttachmentListParams {
  page?: number
  pageSize?: number
}

export interface AttachmentListResponse {
  items: Attachment[]
  total: number
  limit: number
  offset: number
}

const UPLOADS_QUERY_KEY = ["uploads"] as const
const ADMIN_ATTACHMENTS_QUERY_KEY = ["admin", "attachments"] as const

function unwrapErrorMessage(error: unknown): string {
  if (!error) {
    return "An unknown error occurred"
  }
  if (typeof error === "string") {
    return error
  }
  if (error instanceof Error) {
    return error.message
  }
  if (typeof error === "object") {
    const err = error as Record<string, unknown>
    if (typeof err.detail === "string") {
      return err.detail
    }
    if (typeof err.message === "string") {
      return err.message
    }
  }
  return "An unknown error occurred"
}

function getApiBaseUrl(): string {
  // Match the configuration applied in main.tsx via `client.setConfig`.
  const fromConfig = client.getConfig().baseUrl
  if (typeof fromConfig === "string") {
    return fromConfig
  }
  return ""
}

function getAccessToken(): string | null {
  if (typeof window === "undefined") {
    return null
  }
  return window.localStorage.getItem("access_token")
}

// Re-declare the global the litestar-vite plugin injects so this file doesn't
// rely on the augmentation in `main.tsx` being in the tsconfig include path.
declare global {
  interface Window {
    __LITESTAR_CSRF__?: string
  }
}

function getCsrfToken(): string | undefined {
  if (typeof window === "undefined") {
    return undefined
  }
  return window.__LITESTAR_CSRF__
}

/**
 * Uploads a file via XMLHttpRequest so we can surface progress events. The
 * generated `client` uses `fetch`, which does not expose upload progress.
 *
 * Authentication mirrors what `client.setConfig` does in `main.tsx`: pull the
 * bearer token from localStorage, include credentials so the auth cookie is
 * sent, and add the CSRF header for unsafe methods when present.
 */
function uploadWithProgress(args: {
  url: string
  method?: "POST" | "PUT"
  file: File
  fieldName?: string
  onProgress?: (pct: number) => void
  signal?: AbortSignal
}): Promise<unknown> {
  const { url, method = "POST", file, fieldName = "data", onProgress, signal } = args

  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest()
    const form = new FormData()
    form.append(fieldName, file, file.name)

    const fullUrl = `${getApiBaseUrl()}${url}`
    xhr.open(method, fullUrl, true)
    xhr.withCredentials = true
    xhr.responseType = "text"

    const token = getAccessToken()
    if (token) {
      xhr.setRequestHeader("Authorization", `Bearer ${token}`)
    }
    const csrf = getCsrfToken()
    if (csrf) {
      xhr.setRequestHeader("X-XSRF-TOKEN", csrf)
    }
    // Do not set Content-Type explicitly; the browser sets the multipart
    // boundary automatically when sending FormData.

    if (signal) {
      if (signal.aborted) {
        xhr.abort()
        reject(new DOMException("Upload aborted", "AbortError"))
        return
      }
      signal.addEventListener("abort", () => xhr.abort(), { once: true })
    }

    xhr.upload.onprogress = (event) => {
      if (event.lengthComputable && onProgress) {
        const pct = Math.round((event.loaded / event.total) * 100)
        onProgress(pct)
      }
    }

    xhr.onerror = () => reject(new Error("Network error during upload"))
    xhr.onabort = () => reject(new DOMException("Upload aborted", "AbortError"))

    xhr.onload = () => {
      const text = xhr.responseText
      let body: unknown = text
      if (text) {
        try {
          body = JSON.parse(text)
        } catch {
          // leave as text
        }
      }
      if (xhr.status >= 200 && xhr.status < 300) {
        resolve(body)
        return
      }
      reject(body ?? new Error(`Upload failed with status ${xhr.status}`))
    }

    xhr.send(form)
  })
}

/**
 * Paginated list of the current user's uploads (superusers see all).
 */
export function useUploads(params: AttachmentListParams = {}) {
  const { page = 1, pageSize = 25 } = params
  return useQuery({
    queryKey: [...UPLOADS_QUERY_KEY, page, pageSize],
    queryFn: async () => {
      const result = await client.get({
        url: "/api/uploads",
        query: { currentPage: page, pageSize },
      })
      if (result.error) {
        throw result.error
      }
      return result.data as AttachmentListResponse
    },
  })
}

export function useAttachment(id: string | undefined) {
  return useQuery({
    queryKey: [...UPLOADS_QUERY_KEY, "detail", id],
    enabled: !!id,
    queryFn: async () => {
      const result = await client.get({
        url: "/api/uploads/{id}",
        path: { id: id as string },
      })
      if (result.error) {
        throw result.error
      }
      return result.data as Attachment
    },
  })
}

export interface UploadFileVariables {
  file: File
  purpose?: AttachmentPurpose
  onProgress?: (pct: number) => void
  signal?: AbortSignal
}

export function useUploadFile() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: async ({ file, purpose, onProgress, signal }: UploadFileVariables) => {
      if (file.size > MAX_UPLOAD_SIZE_BYTES) {
        throw new Error(`File exceeds the ${Math.floor(MAX_UPLOAD_SIZE_BYTES / (1024 * 1024))} MiB upload limit.`)
      }
      const qs = purpose ? `?purpose=${encodeURIComponent(purpose)}` : ""
      const result = (await uploadWithProgress({
        url: `/api/uploads${qs}`,
        method: "POST",
        file,
        onProgress,
        signal,
      })) as Attachment
      return result
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: UPLOADS_QUERY_KEY })
      queryClient.invalidateQueries({ queryKey: ADMIN_ATTACHMENTS_QUERY_KEY })
    },
    onError: (error) => {
      toast.error("Upload failed", { description: unwrapErrorMessage(error) })
    },
  })
}

export function useDeleteAttachment() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: async (id: string) => {
      const result = await client.delete({
        url: "/api/uploads/{id}",
        path: { id },
      })
      if (result.error) {
        throw result.error
      }
      return id
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: UPLOADS_QUERY_KEY })
      queryClient.invalidateQueries({ queryKey: ADMIN_ATTACHMENTS_QUERY_KEY })
      toast.success("Attachment deleted")
    },
    onError: (error) => {
      toast.error("Unable to delete attachment", { description: unwrapErrorMessage(error) })
    },
  })
}

export function useSetAvatar() {
  const queryClient = useQueryClient()
  const checkAuth = useAuthStore((state) => state.checkAuth)
  return useMutation({
    mutationFn: async ({ file, onProgress, signal }: { file: File; onProgress?: (pct: number) => void; signal?: AbortSignal }) => {
      if (file.size > MAX_UPLOAD_SIZE_BYTES) {
        throw new Error(`File exceeds the ${Math.floor(MAX_UPLOAD_SIZE_BYTES / (1024 * 1024))} MiB upload limit.`)
      }
      const result = await uploadWithProgress({
        url: "/api/me/avatar",
        method: "PUT",
        file,
        onProgress,
        signal,
      })
      return result
    },
    onSuccess: async () => {
      queryClient.invalidateQueries({ queryKey: UPLOADS_QUERY_KEY })
      // Refresh the user payload held in the zustand auth store so that the
      // freshly set avatarUrl is reflected throughout the app (sidebar etc.).
      await checkAuth()
      toast.success("Avatar updated")
    },
    onError: (error) => {
      toast.error("Unable to update avatar", { description: unwrapErrorMessage(error) })
    },
  })
}

export function useClearAvatar() {
  const queryClient = useQueryClient()
  const checkAuth = useAuthStore((state) => state.checkAuth)
  return useMutation({
    mutationFn: async () => {
      const result = await client.delete({ url: "/api/me/avatar" })
      if (result.error) {
        throw result.error
      }
      return result.data
    },
    onSuccess: async () => {
      queryClient.invalidateQueries({ queryKey: UPLOADS_QUERY_KEY })
      await checkAuth()
      toast.success("Avatar removed")
    },
    onError: (error) => {
      toast.error("Unable to remove avatar", { description: unwrapErrorMessage(error) })
    },
  })
}

export function useSetTeamLogo(teamId: string | undefined) {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: async ({ file, onProgress, signal }: { file: File; onProgress?: (pct: number) => void; signal?: AbortSignal }) => {
      if (!teamId) {
        throw new Error("Missing team id")
      }
      if (file.size > MAX_UPLOAD_SIZE_BYTES) {
        throw new Error(`File exceeds the ${Math.floor(MAX_UPLOAD_SIZE_BYTES / (1024 * 1024))} MiB upload limit.`)
      }
      const result = await uploadWithProgress({
        url: `/api/teams/${encodeURIComponent(teamId)}/logo`,
        method: "PUT",
        file,
        onProgress,
        signal,
      })
      return result
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: UPLOADS_QUERY_KEY })
      if (teamId) {
        queryClient.invalidateQueries({ queryKey: ["teams"] })
        queryClient.invalidateQueries({ queryKey: ["team", teamId] })
      }
      toast.success("Team logo updated")
    },
    onError: (error) => {
      toast.error("Unable to update team logo", { description: unwrapErrorMessage(error) })
    },
  })
}

/**
 * Superuser-only paginated list of every attachment in the system.
 */
export function useAdminAttachments(params: AttachmentListParams = {}) {
  const { page = 1, pageSize = 25 } = params
  return useQuery({
    queryKey: [...ADMIN_ATTACHMENTS_QUERY_KEY, page, pageSize],
    queryFn: async () => {
      const result = await client.get({
        url: "/api/admin/attachments",
        query: { currentPage: page, pageSize },
      })
      if (result.error) {
        throw result.error
      }
      return result.data as AttachmentListResponse
    },
  })
}

/**
 * Fetches an authenticated attachment's bytes and returns a blob:// URL that
 * can be used as the source for `<img>`, `<a download>`, etc. Useful when the
 * caller cannot rely on the browser sending auth headers for the bare URL.
 *
 * The caller is responsible for revoking the returned URL via
 * `URL.revokeObjectURL` once it is no longer needed.
 */
export async function fetchAttachmentObjectUrl(attachmentId: string): Promise<string> {
  const result = await client.get({
    url: "/api/uploads/{id}/content",
    path: { id: attachmentId },
    parseAs: "blob",
  })
  if (result.error) {
    throw result.error
  }
  const blob = result.data as Blob
  return URL.createObjectURL(blob)
}

/**
 * Convenience: triggers a browser-side "Save as" by fetching the attachment
 * with auth and clicking a synthetic anchor.
 */
export async function downloadAttachment(attachment: Pick<Attachment, "id" | "originalFilename">): Promise<void> {
  const objectUrl = await fetchAttachmentObjectUrl(attachment.id)
  const anchor = document.createElement("a")
  anchor.href = objectUrl
  anchor.download = attachment.originalFilename || `attachment-${attachment.id}`
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  // Defer revocation so the navigation has time to begin.
  setTimeout(() => URL.revokeObjectURL(objectUrl), 1000)
}

/**
 * Human-readable byte size helper, used by attachment-related UI. Uses
 * binary (1024-based) units to match the server's MAX_UPLOAD_BYTES which is
 * expressed in MiB.
 */
export function formatBytes(bytes: number): string {
  if (!Number.isFinite(bytes) || bytes < 0) {
    return "—"
  }
  if (bytes === 0) {
    return "0 B"
  }
  const units = ["B", "KiB", "MiB", "GiB", "TiB"]
  const exp = Math.min(units.length - 1, Math.floor(Math.log(bytes) / Math.log(1024)))
  const value = bytes / 1024 ** exp
  return `${value.toFixed(value >= 10 || exp === 0 ? 0 : 1)} ${units[exp]}`
}
