/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicVerifyEmailRouteImport } from './routes/_public/verify-email'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicMfaChallengeRouteImport } from './routes/_public/mfa-challenge'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicLandingRouteImport } from './routes/_public/landing'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AppTeamsRouteImport } from './routes/_app/teams'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppDevicesRouteImport } from './routes/_app/devices'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppVoiceIndexRouteImport } from './routes/_app/voice/index'
import { Route as AppTeamsIndexRouteImport } from './routes/_app/teams/index'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppDevicesIndexRouteImport } from './routes/_app/devices/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppVoicePhoneNumbersRouteImport } from './routes/_app/voice/phone-numbers'
import { Route as AppTeamsNewRouteImport } from './routes/_app/teams/new'
import { Route as AppTeamsTeamIdRouteImport } from './routes/_app/teams/$teamId'
import { Route as AppDevicesNewRouteImport } from './routes/_app/devices/new'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'
import { Route as AppVoiceExtensionsIndexRouteImport } from './routes/_app/voice/extensions/index'
import { Route as AppDevicesDeviceIdIndexRouteImport } from './routes/_app/devices/$deviceId/index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users/index'
import { Route as AppAdminTeamsIndexRouteImport } from './routes/_app/admin/teams/index'
import { Route as PublicAuthGoogleCallbackRouteImport } from './routes/_public/auth/google/callback'
import { Route as PublicAuthGithubCallbackRouteImport } from './routes/_public/auth/github/callback'
import { Route as AppAdminUsersUserIdRouteImport } from './routes/_app/admin/users/$userId'
import { Route as AppAdminTeamsTeamIdRouteImport } from './routes/_app/admin/teams/$teamId'
import { Route as AppVoiceExtensionsExtensionIdIndexRouteImport } from './routes/_app/voice/extensions/$extensionId/index'
import { Route as AppTeamsTeamIdInvitationsInvitationIdAcceptRouteImport } from './routes/_app/teams/$teamId/invitations/$invitationId/accept'
import { Route as AppFaxIndexRouteImport } from './routes/_app/fax/index'
import { Route as AppFaxSendRouteImport } from './routes/_app/fax/send'
import { Route as AppFaxNumbersIndexRouteImport } from './routes/_app/fax/numbers/index'
import { Route as AppFaxNumbersFaxNumberIdIndexRouteImport } from './routes/_app/fax/numbers/$faxNumberId/index'
import { Route as AppFaxMessagesIndexRouteImport } from './routes/_app/fax/messages/index'
import { Route as AppFaxMessagesMessageIdIndexRouteImport } from './routes/_app/fax/messages/$messageId/index'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppSupportIndexRouteImport } from './routes/_app/support/index'
import { Route as AppSupportNewRouteImport } from './routes/_app/support/new'
import { Route as AppSupportTicketIdIndexRouteImport } from './routes/_app/support/$ticketId/index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicVerifyEmailRoute = PublicVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMfaChallengeRoute = PublicMfaChallengeRouteImport.update({
  id: '/mfa-challenge',
  path: '/mfa-challenge',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLandingRoute = PublicLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceIndexRoute = AppVoiceIndexRouteImport.update({
  id: '/voice/',
  path: '/voice/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsIndexRoute = AppTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTeamsRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesIndexRoute = AppDevicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDevicesRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppVoicePhoneNumbersRoute = AppVoicePhoneNumbersRouteImport.update({
  id: '/voice/phone-numbers',
  path: '/voice/phone-numbers',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsNewRoute = AppTeamsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTeamsRoute,
} as any)
const AppTeamsTeamIdRoute = AppTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => AppTeamsRoute,
} as any)
const AppDevicesNewRoute = AppDevicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDevicesRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppVoiceExtensionsIndexRoute = AppVoiceExtensionsIndexRouteImport.update({
  id: '/voice/extensions/',
  path: '/voice/extensions/',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesDeviceIdIndexRoute = AppDevicesDeviceIdIndexRouteImport.update({
  id: '/$deviceId/',
  path: '/$deviceId/',
  getParentRoute: () => AppDevicesRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTeamsIndexRoute = AppAdminTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AppAdminRoute,
} as any)
const PublicAuthGoogleCallbackRoute =
  PublicAuthGoogleCallbackRouteImport.update({
    id: '/auth/google/callback',
    path: '/auth/google/callback',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAuthGithubCallbackRoute =
  PublicAuthGithubCallbackRouteImport.update({
    id: '/auth/github/callback',
    path: '/auth/github/callback',
    getParentRoute: () => PublicRoute,
  } as any)
const AppAdminUsersUserIdRoute = AppAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTeamsTeamIdRoute = AppAdminTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppVoiceExtensionsExtensionIdIndexRoute =
  AppVoiceExtensionsExtensionIdIndexRouteImport.update({
    id: '/voice/extensions/$extensionId/',
    path: '/voice/extensions/$extensionId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppTeamsTeamIdInvitationsInvitationIdAcceptRoute =
  AppTeamsTeamIdInvitationsInvitationIdAcceptRouteImport.update({
    id: '/invitations/$invitationId/accept',
    path: '/invitations/$invitationId/accept',
    getParentRoute: () => AppTeamsTeamIdRoute,
  } as any)
const AppFaxIndexRoute = AppFaxIndexRouteImport.update({
  id: '/fax/',
  path: '/fax/',
  getParentRoute: () => AppRoute,
} as any)
const AppFaxSendRoute = AppFaxSendRouteImport.update({
  id: '/fax/send',
  path: '/fax/send',
  getParentRoute: () => AppRoute,
} as any)
const AppFaxNumbersIndexRoute = AppFaxNumbersIndexRouteImport.update({
  id: '/fax/numbers/',
  path: '/fax/numbers/',
  getParentRoute: () => AppRoute,
} as any)
const AppFaxNumbersFaxNumberIdIndexRoute = AppFaxNumbersFaxNumberIdIndexRouteImport.update({
  id: '/fax/numbers/$faxNumberId/',
  path: '/fax/numbers/$faxNumberId/',
  getParentRoute: () => AppRoute,
} as any)
const AppFaxMessagesIndexRoute = AppFaxMessagesIndexRouteImport.update({
  id: '/fax/messages/',
  path: '/fax/messages/',
  getParentRoute: () => AppRoute,
} as any)
const AppFaxMessagesMessageIdIndexRoute = AppFaxMessagesMessageIdIndexRouteImport.update({
  id: '/fax/messages/$messageId/',
  path: '/fax/messages/$messageId/',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportIndexRoute = AppSupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSupportRoute,
} as any)
const AppSupportNewRoute = AppSupportNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSupportRoute,
} as any)
const AppSupportTicketIdIndexRoute = AppSupportTicketIdIndexRouteImport.update({
  id: '/$ticketId/',
  path: '/$ticketId/',
  getParentRoute: () => AppSupportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/devices': typeof AppDevicesRouteWithChildren
  '/home': typeof AppHomeRoute
  '/teams': typeof AppTeamsRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/landing': typeof PublicLandingRoute
  '/login': typeof PublicLoginRoute
  '/mfa-challenge': typeof PublicMfaChallengeRoute
  '/privacy': typeof PublicPrivacyRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/signup': typeof PublicSignupRoute
  '/terms': typeof PublicTermsRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/devices/new': typeof AppDevicesNewRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRouteWithChildren
  '/teams/new': typeof AppTeamsNewRoute
  '/voice/phone-numbers': typeof AppVoicePhoneNumbersRoute
  '/admin/': typeof AppAdminIndexRoute
  '/devices/': typeof AppDevicesIndexRoute
  '/profile/': typeof AppProfileIndexRoute
  '/teams/': typeof AppTeamsIndexRoute
  '/voice/': typeof AppVoiceIndexRoute
  '/admin/teams/$teamId': typeof AppAdminTeamsTeamIdRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/auth/github/callback': typeof PublicAuthGithubCallbackRoute
  '/auth/google/callback': typeof PublicAuthGoogleCallbackRoute
  '/admin/teams/': typeof AppAdminTeamsIndexRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
  '/devices/$deviceId/': typeof AppDevicesDeviceIdIndexRoute
  '/voice/extensions/': typeof AppVoiceExtensionsIndexRoute
  '/voice/extensions/$extensionId/': typeof AppVoiceExtensionsExtensionIdIndexRoute
  '/teams/$teamId/invitations/$invitationId/accept': typeof AppTeamsTeamIdInvitationsInvitationIdAcceptRoute
  '/fax/': typeof AppFaxIndexRoute
  '/fax/send': typeof AppFaxSendRoute
  '/fax/numbers/': typeof AppFaxNumbersIndexRoute
  '/fax/numbers/$faxNumberId/': typeof AppFaxNumbersFaxNumberIdIndexRoute
  '/fax/messages/': typeof AppFaxMessagesIndexRoute
  '/fax/messages/$messageId/': typeof AppFaxMessagesMessageIdIndexRoute
  '/support': typeof AppSupportRouteWithChildren
  '/support/new': typeof AppSupportNewRoute
  '/support/': typeof AppSupportIndexRoute
  '/support/$ticketId/': typeof AppSupportTicketIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/home': typeof AppHomeRoute
  '/about': typeof PublicAboutRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/landing': typeof PublicLandingRoute
  '/login': typeof PublicLoginRoute
  '/mfa-challenge': typeof PublicMfaChallengeRoute
  '/privacy': typeof PublicPrivacyRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/signup': typeof PublicSignupRoute
  '/terms': typeof PublicTermsRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/devices/new': typeof AppDevicesNewRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRouteWithChildren
  '/teams/new': typeof AppTeamsNewRoute
  '/voice/phone-numbers': typeof AppVoicePhoneNumbersRoute
  '/admin': typeof AppAdminIndexRoute
  '/devices': typeof AppDevicesIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/teams': typeof AppTeamsIndexRoute
  '/voice': typeof AppVoiceIndexRoute
  '/admin/teams/$teamId': typeof AppAdminTeamsTeamIdRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/auth/github/callback': typeof PublicAuthGithubCallbackRoute
  '/auth/google/callback': typeof PublicAuthGoogleCallbackRoute
  '/admin/teams': typeof AppAdminTeamsIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/devices/$deviceId': typeof AppDevicesDeviceIdIndexRoute
  '/voice/extensions': typeof AppVoiceExtensionsIndexRoute
  '/voice/extensions/$extensionId': typeof AppVoiceExtensionsExtensionIdIndexRoute
  '/teams/$teamId/invitations/$invitationId/accept': typeof AppTeamsTeamIdInvitationsInvitationIdAcceptRoute
  '/fax': typeof AppFaxIndexRoute
  '/fax/send': typeof AppFaxSendRoute
  '/fax/numbers': typeof AppFaxNumbersIndexRoute
  '/fax/numbers/$faxNumberId': typeof AppFaxNumbersFaxNumberIdIndexRoute
  '/fax/messages': typeof AppFaxMessagesIndexRoute
  '/fax/messages/$messageId': typeof AppFaxMessagesMessageIdIndexRoute
  '/support': typeof AppSupportIndexRoute
  '/support/new': typeof AppSupportNewRoute
  '/support/$ticketId': typeof AppSupportTicketIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/devices': typeof AppDevicesRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/teams': typeof AppTeamsRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/landing': typeof PublicLandingRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/mfa-challenge': typeof PublicMfaChallengeRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/verify-email': typeof PublicVerifyEmailRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/devices/new': typeof AppDevicesNewRoute
  '/_app/teams/$teamId': typeof AppTeamsTeamIdRouteWithChildren
  '/_app/teams/new': typeof AppTeamsNewRoute
  '/_app/voice/phone-numbers': typeof AppVoicePhoneNumbersRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/devices/': typeof AppDevicesIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/teams/': typeof AppTeamsIndexRoute
  '/_app/voice/': typeof AppVoiceIndexRoute
  '/_app/admin/teams/$teamId': typeof AppAdminTeamsTeamIdRoute
  '/_app/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/_public/auth/github/callback': typeof PublicAuthGithubCallbackRoute
  '/_public/auth/google/callback': typeof PublicAuthGoogleCallbackRoute
  '/_app/admin/teams/': typeof AppAdminTeamsIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/devices/$deviceId/': typeof AppDevicesDeviceIdIndexRoute
  '/_app/voice/extensions/': typeof AppVoiceExtensionsIndexRoute
  '/_app/voice/extensions/$extensionId/': typeof AppVoiceExtensionsExtensionIdIndexRoute
  '/_app/teams/$teamId/invitations/$invitationId/accept': typeof AppTeamsTeamIdInvitationsInvitationIdAcceptRoute
  '/_app/fax/': typeof AppFaxIndexRoute
  '/_app/fax/send': typeof AppFaxSendRoute
  '/_app/fax/numbers/': typeof AppFaxNumbersIndexRoute
  '/_app/fax/numbers/$faxNumberId/': typeof AppFaxNumbersFaxNumberIdIndexRoute
  '/_app/fax/messages/': typeof AppFaxMessagesIndexRoute
  '/_app/fax/messages/$messageId/': typeof AppFaxMessagesMessageIdIndexRoute
  '/_app/support': typeof AppSupportRouteWithChildren
  '/_app/support/': typeof AppSupportIndexRoute
  '/_app/support/new': typeof AppSupportNewRoute
  '/_app/support/$ticketId/': typeof AppSupportTicketIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/devices'
    | '/home'
    | '/teams'
    | '/about'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/mfa-challenge'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/audit'
    | '/devices/new'
    | '/teams/$teamId'
    | '/teams/new'
    | '/voice/phone-numbers'
    | '/admin/'
    | '/devices/'
    | '/profile/'
    | '/teams/'
    | '/voice/'
    | '/admin/teams/$teamId'
    | '/admin/users/$userId'
    | '/auth/github/callback'
    | '/auth/google/callback'
    | '/admin/teams/'
    | '/admin/users/'
    | '/devices/$deviceId/'
    | '/voice/extensions/'
    | '/voice/extensions/$extensionId/'
    | '/teams/$teamId/invitations/$invitationId/accept'
    | '/fax/'
    | '/fax/send'
    | '/fax/numbers/'
    | '/fax/numbers/$faxNumberId/'
    | '/fax/messages/'
    | '/fax/messages/$messageId/'
    | '/support'
    | '/support/new'
    | '/support/'
    | '/support/$ticketId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/home'
    | '/about'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/mfa-challenge'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/audit'
    | '/devices/new'
    | '/teams/$teamId'
    | '/teams/new'
    | '/voice/phone-numbers'
    | '/admin'
    | '/devices'
    | '/profile'
    | '/teams'
    | '/voice'
    | '/admin/teams/$teamId'
    | '/admin/users/$userId'
    | '/auth/github/callback'
    | '/auth/google/callback'
    | '/admin/teams'
    | '/admin/users'
    | '/devices/$deviceId'
    | '/voice/extensions'
    | '/voice/extensions/$extensionId'
    | '/teams/$teamId/invitations/$invitationId/accept'
    | '/fax'
    | '/fax/send'
    | '/fax/numbers'
    | '/fax/numbers/$faxNumberId'
    | '/fax/messages'
    | '/fax/messages/$messageId'
    | '/support'
    | '/support/new'
    | '/support/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_app'
    | '/_public'
    | '/_app/admin'
    | '/_app/devices'
    | '/_app/home'
    | '/_app/teams'
    | '/_public/about'
    | '/_public/forgot-password'
    | '/_public/landing'
    | '/_public/login'
    | '/_public/mfa-challenge'
    | '/_public/privacy'
    | '/_public/reset-password'
    | '/_public/signup'
    | '/_public/terms'
    | '/_public/verify-email'
    | '/_app/admin/audit'
    | '/_app/devices/new'
    | '/_app/teams/$teamId'
    | '/_app/teams/new'
    | '/_app/voice/phone-numbers'
    | '/_app/admin/'
    | '/_app/devices/'
    | '/_app/profile/'
    | '/_app/teams/'
    | '/_app/voice/'
    | '/_app/admin/teams/$teamId'
    | '/_app/admin/users/$userId'
    | '/_public/auth/github/callback'
    | '/_public/auth/google/callback'
    | '/_app/admin/teams/'
    | '/_app/admin/users/'
    | '/_app/devices/$deviceId/'
    | '/_app/voice/extensions/'
    | '/_app/voice/extensions/$extensionId/'
    | '/_app/teams/$teamId/invitations/$invitationId/accept'
    | '/_app/fax/'
    | '/_app/fax/send'
    | '/_app/fax/numbers/'
    | '/_app/fax/numbers/$faxNumberId/'
    | '/_app/fax/messages/'
    | '/_app/fax/messages/$messageId/'
    | '/_app/support'
    | '/_app/support/'
    | '/_app/support/new'
    | '/_app/support/$ticketId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/verify-email': {
      id: '/_public/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicVerifyEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/mfa-challenge': {
      id: '/_public/mfa-challenge'
      path: '/mfa-challenge'
      fullPath: '/mfa-challenge'
      preLoaderRoute: typeof PublicMfaChallengeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/landing': {
      id: '/_public/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof PublicLandingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voice/': {
      id: '/_app/voice/'
      path: '/voice'
      fullPath: '/voice/'
      preLoaderRoute: typeof AppVoiceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/': {
      id: '/_app/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof AppTeamsIndexRouteImport
      parentRoute: typeof AppTeamsRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices/': {
      id: '/_app/devices/'
      path: '/'
      fullPath: '/devices/'
      preLoaderRoute: typeof AppDevicesIndexRouteImport
      parentRoute: typeof AppDevicesRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/voice/phone-numbers': {
      id: '/_app/voice/phone-numbers'
      path: '/voice/phone-numbers'
      fullPath: '/voice/phone-numbers'
      preLoaderRoute: typeof AppVoicePhoneNumbersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/new': {
      id: '/_app/teams/new'
      path: '/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof AppTeamsNewRouteImport
      parentRoute: typeof AppTeamsRoute
    }
    '/_app/teams/$teamId': {
      id: '/_app/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AppTeamsTeamIdRouteImport
      parentRoute: typeof AppTeamsRoute
    }
    '/_app/devices/new': {
      id: '/_app/devices/new'
      path: '/new'
      fullPath: '/devices/new'
      preLoaderRoute: typeof AppDevicesNewRouteImport
      parentRoute: typeof AppDevicesRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/voice/extensions/': {
      id: '/_app/voice/extensions/'
      path: '/voice/extensions'
      fullPath: '/voice/extensions/'
      preLoaderRoute: typeof AppVoiceExtensionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices/$deviceId/': {
      id: '/_app/devices/$deviceId/'
      path: '/$deviceId'
      fullPath: '/devices/$deviceId/'
      preLoaderRoute: typeof AppDevicesDeviceIdIndexRouteImport
      parentRoute: typeof AppDevicesRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/teams/': {
      id: '/_app/admin/teams/'
      path: '/teams'
      fullPath: '/admin/teams/'
      preLoaderRoute: typeof AppAdminTeamsIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_public/auth/google/callback': {
      id: '/_public/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof PublicAuthGoogleCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/github/callback': {
      id: '/_public/auth/github/callback'
      path: '/auth/github/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof PublicAuthGithubCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/admin/users/$userId': {
      id: '/_app/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AppAdminUsersUserIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/teams/$teamId': {
      id: '/_app/admin/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/admin/teams/$teamId'
      preLoaderRoute: typeof AppAdminTeamsTeamIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/voice/extensions/$extensionId/': {
      id: '/_app/voice/extensions/$extensionId/'
      path: '/voice/extensions/$extensionId'
      fullPath: '/voice/extensions/$extensionId/'
      preLoaderRoute: typeof AppVoiceExtensionsExtensionIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId/invitations/$invitationId/accept': {
      id: '/_app/teams/$teamId/invitations/$invitationId/accept'
      path: '/invitations/$invitationId/accept'
      fullPath: '/teams/$teamId/invitations/$invitationId/accept'
      preLoaderRoute: typeof AppTeamsTeamIdInvitationsInvitationIdAcceptRouteImport
      parentRoute: typeof AppTeamsTeamIdRoute
    }
    '/_app/fax/': {
      id: '/_app/fax/'
      path: '/fax'
      fullPath: '/fax/'
      preLoaderRoute: typeof AppFaxIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fax/send': {
      id: '/_app/fax/send'
      path: '/fax/send'
      fullPath: '/fax/send'
      preLoaderRoute: typeof AppFaxSendRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fax/numbers/': {
      id: '/_app/fax/numbers/'
      path: '/fax/numbers'
      fullPath: '/fax/numbers/'
      preLoaderRoute: typeof AppFaxNumbersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fax/numbers/$faxNumberId/': {
      id: '/_app/fax/numbers/$faxNumberId/'
      path: '/fax/numbers/$faxNumberId'
      fullPath: '/fax/numbers/$faxNumberId/'
      preLoaderRoute: typeof AppFaxNumbersFaxNumberIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fax/messages/': {
      id: '/_app/fax/messages/'
      path: '/fax/messages'
      fullPath: '/fax/messages/'
      preLoaderRoute: typeof AppFaxMessagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fax/messages/$messageId/': {
      id: '/_app/fax/messages/$messageId/'
      path: '/fax/messages/$messageId'
      fullPath: '/fax/messages/$messageId/'
      preLoaderRoute: typeof AppFaxMessagesMessageIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/': {
      id: '/_app/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof AppSupportIndexRouteImport
      parentRoute: typeof AppSupportRoute
    }
    '/_app/support/new': {
      id: '/_app/support/new'
      path: '/new'
      fullPath: '/support/new'
      preLoaderRoute: typeof AppSupportNewRouteImport
      parentRoute: typeof AppSupportRoute
    }
    '/_app/support/$ticketId/': {
      id: '/_app/support/$ticketId/'
      path: '/$ticketId'
      fullPath: '/support/$ticketId/'
      preLoaderRoute: typeof AppSupportTicketIdIndexRouteImport
      parentRoute: typeof AppSupportRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminTeamsTeamIdRoute: typeof AppAdminTeamsTeamIdRoute
  AppAdminUsersUserIdRoute: typeof AppAdminUsersUserIdRoute
  AppAdminTeamsIndexRoute: typeof AppAdminTeamsIndexRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminTeamsTeamIdRoute: AppAdminTeamsTeamIdRoute,
  AppAdminUsersUserIdRoute: AppAdminUsersUserIdRoute,
  AppAdminTeamsIndexRoute: AppAdminTeamsIndexRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppDevicesRouteChildren {
  AppDevicesNewRoute: typeof AppDevicesNewRoute
  AppDevicesIndexRoute: typeof AppDevicesIndexRoute
  AppDevicesDeviceIdIndexRoute: typeof AppDevicesDeviceIdIndexRoute
}

const AppDevicesRouteChildren: AppDevicesRouteChildren = {
  AppDevicesNewRoute: AppDevicesNewRoute,
  AppDevicesIndexRoute: AppDevicesIndexRoute,
  AppDevicesDeviceIdIndexRoute: AppDevicesDeviceIdIndexRoute,
}

const AppDevicesRouteWithChildren = AppDevicesRoute._addFileChildren(
  AppDevicesRouteChildren,
)

interface AppTeamsTeamIdRouteChildren {
  AppTeamsTeamIdInvitationsInvitationIdAcceptRoute: typeof AppTeamsTeamIdInvitationsInvitationIdAcceptRoute
}

const AppTeamsTeamIdRouteChildren: AppTeamsTeamIdRouteChildren = {
  AppTeamsTeamIdInvitationsInvitationIdAcceptRoute:
    AppTeamsTeamIdInvitationsInvitationIdAcceptRoute,
}

const AppTeamsTeamIdRouteWithChildren = AppTeamsTeamIdRoute._addFileChildren(
  AppTeamsTeamIdRouteChildren,
)

interface AppTeamsRouteChildren {
  AppTeamsTeamIdRoute: typeof AppTeamsTeamIdRouteWithChildren
  AppTeamsNewRoute: typeof AppTeamsNewRoute
  AppTeamsIndexRoute: typeof AppTeamsIndexRoute
}

const AppTeamsRouteChildren: AppTeamsRouteChildren = {
  AppTeamsTeamIdRoute: AppTeamsTeamIdRouteWithChildren,
  AppTeamsNewRoute: AppTeamsNewRoute,
  AppTeamsIndexRoute: AppTeamsIndexRoute,
}

const AppTeamsRouteWithChildren = AppTeamsRoute._addFileChildren(
  AppTeamsRouteChildren,
)

interface AppSupportRouteChildren {
  AppSupportIndexRoute: typeof AppSupportIndexRoute
  AppSupportNewRoute: typeof AppSupportNewRoute
  AppSupportTicketIdIndexRoute: typeof AppSupportTicketIdIndexRoute
}

const AppSupportRouteChildren: AppSupportRouteChildren = {
  AppSupportIndexRoute: AppSupportIndexRoute,
  AppSupportNewRoute: AppSupportNewRoute,
  AppSupportTicketIdIndexRoute: AppSupportTicketIdIndexRoute,
}

const AppSupportRouteWithChildren = AppSupportRoute._addFileChildren(
  AppSupportRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDevicesRoute: typeof AppDevicesRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppTeamsRoute: typeof AppTeamsRouteWithChildren
  AppSupportRoute: typeof AppSupportRouteWithChildren
  AppVoicePhoneNumbersRoute: typeof AppVoicePhoneNumbersRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppVoiceIndexRoute: typeof AppVoiceIndexRoute
  AppVoiceExtensionsIndexRoute: typeof AppVoiceExtensionsIndexRoute
  AppVoiceExtensionsExtensionIdIndexRoute: typeof AppVoiceExtensionsExtensionIdIndexRoute
  AppFaxIndexRoute: typeof AppFaxIndexRoute
  AppFaxSendRoute: typeof AppFaxSendRoute
  AppFaxNumbersIndexRoute: typeof AppFaxNumbersIndexRoute
  AppFaxNumbersFaxNumberIdIndexRoute: typeof AppFaxNumbersFaxNumberIdIndexRoute
  AppFaxMessagesIndexRoute: typeof AppFaxMessagesIndexRoute
  AppFaxMessagesMessageIdIndexRoute: typeof AppFaxMessagesMessageIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDevicesRoute: AppDevicesRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppTeamsRoute: AppTeamsRouteWithChildren,
  AppSupportRoute: AppSupportRouteWithChildren,
  AppVoicePhoneNumbersRoute: AppVoicePhoneNumbersRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppVoiceIndexRoute: AppVoiceIndexRoute,
  AppVoiceExtensionsIndexRoute: AppVoiceExtensionsIndexRoute,
  AppVoiceExtensionsExtensionIdIndexRoute:
    AppVoiceExtensionsExtensionIdIndexRoute,
  AppFaxIndexRoute: AppFaxIndexRoute,
  AppFaxSendRoute: AppFaxSendRoute,
  AppFaxNumbersIndexRoute: AppFaxNumbersIndexRoute,
  AppFaxNumbersFaxNumberIdIndexRoute: AppFaxNumbersFaxNumberIdIndexRoute,
  AppFaxMessagesIndexRoute: AppFaxMessagesIndexRoute,
  AppFaxMessagesMessageIdIndexRoute: AppFaxMessagesMessageIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLandingRoute: typeof PublicLandingRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicMfaChallengeRoute: typeof PublicMfaChallengeRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicSignupRoute: typeof PublicSignupRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicVerifyEmailRoute: typeof PublicVerifyEmailRoute
  PublicAuthGithubCallbackRoute: typeof PublicAuthGithubCallbackRoute
  PublicAuthGoogleCallbackRoute: typeof PublicAuthGoogleCallbackRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLandingRoute: PublicLandingRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicMfaChallengeRoute: PublicMfaChallengeRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicSignupRoute: PublicSignupRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicVerifyEmailRoute: PublicVerifyEmailRoute,
  PublicAuthGithubCallbackRoute: PublicAuthGithubCallbackRoute,
  PublicAuthGoogleCallbackRoute: PublicAuthGoogleCallbackRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
