/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicVerifyEmailRouteImport } from './routes/_public/verify-email'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicMfaChallengeRouteImport } from './routes/_public/mfa-challenge'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicLandingRouteImport } from './routes/_public/landing'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AppTeamsRouteImport } from './routes/_app/teams'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppOrganizationRouteImport } from './routes/_app/organization'
import { Route as AppLocationsRouteImport } from './routes/_app/locations'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppDevicesRouteImport } from './routes/_app/devices'
import { Route as AppConnectionsRouteImport } from './routes/_app/connections'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppVoiceIndexRouteImport } from './routes/_app/voice/index'
import { Route as AppTeamsIndexRouteImport } from './routes/_app/teams/index'
import { Route as AppTagsIndexRouteImport } from './routes/_app/tags/index'
import { Route as AppSupportIndexRouteImport } from './routes/_app/support/index'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppOrganizationIndexRouteImport } from './routes/_app/organization/index'
import { Route as AppNotificationsIndexRouteImport } from './routes/_app/notifications/index'
import { Route as AppLocationsIndexRouteImport } from './routes/_app/locations/index'
import { Route as AppGatewayIndexRouteImport } from './routes/_app/gateway/index'
import { Route as AppFaxIndexRouteImport } from './routes/_app/fax/index'
import { Route as AppDevicesIndexRouteImport } from './routes/_app/devices/index'
import { Route as AppConnectionsIndexRouteImport } from './routes/_app/connections/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppVoicePhoneNumbersRouteImport } from './routes/_app/voice/phone-numbers'
import { Route as AppTeamsNewRouteImport } from './routes/_app/teams/new'
import { Route as AppTagsNewRouteImport } from './routes/_app/tags/new'
import { Route as AppSupportNewRouteImport } from './routes/_app/support/new'
import { Route as AppLocationsNewRouteImport } from './routes/_app/locations/new'
import { Route as AppLocationsLocationIdRouteImport } from './routes/_app/locations/$locationId'
import { Route as AppFaxSendRouteImport } from './routes/_app/fax/send'
import { Route as AppFaxEmailRoutesRouteImport } from './routes/_app/fax/email-routes'
import { Route as AppDevicesNewRouteImport } from './routes/_app/devices/new'
import { Route as AppConnectionsNewRouteImport } from './routes/_app/connections/new'
import { Route as AppConnectionsConnectionIdRouteImport } from './routes/_app/connections/$connectionId'
import { Route as AppAdminVoiceRouteImport } from './routes/_app/admin/voice'
import { Route as AppAdminSystemRouteImport } from './routes/_app/admin/system'
import { Route as AppAdminSupportRouteImport } from './routes/_app/admin/support'
import { Route as AppAdminFaxRouteImport } from './routes/_app/admin/fax'
import { Route as AppAdminDevicesRouteImport } from './routes/_app/admin/devices'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'
import { Route as AppVoiceExtensionsIndexRouteImport } from './routes/_app/voice/extensions/index'
import { Route as AppTeamsTeamIdIndexRouteImport } from './routes/_app/teams/$teamId/index'
import { Route as AppSupportTicketIdIndexRouteImport } from './routes/_app/support/$ticketId/index'
import { Route as AppLocationsLocationIdIndexRouteImport } from './routes/_app/locations/$locationId/index'
import { Route as AppFaxNumbersIndexRouteImport } from './routes/_app/fax/numbers/index'
import { Route as AppFaxMessagesIndexRouteImport } from './routes/_app/fax/messages/index'
import { Route as AppDevicesDeviceIdIndexRouteImport } from './routes/_app/devices/$deviceId/index'
import { Route as AppConnectionsConnectionIdIndexRouteImport } from './routes/_app/connections/$connectionId/index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users/index'
import { Route as AppAdminTeamsIndexRouteImport } from './routes/_app/admin/teams/index'
import { Route as PublicAuthGoogleCallbackRouteImport } from './routes/_public/auth/google/callback'
import { Route as PublicAuthGithubCallbackRouteImport } from './routes/_public/auth/github/callback'
import { Route as AppVoiceExtensionsNewRouteImport } from './routes/_app/voice/extensions/new'
import { Route as AppTagsTagIdEditRouteImport } from './routes/_app/tags/$tagId/edit'
import { Route as AppSupportTicketIdEditRouteImport } from './routes/_app/support/$ticketId/edit'
import { Route as AppFaxNumbersNewRouteImport } from './routes/_app/fax/numbers/new'
import { Route as AppDevicesDeviceIdEditRouteImport } from './routes/_app/devices/$deviceId/edit'
import { Route as AppConnectionsConnectionIdEditRouteImport } from './routes/_app/connections/$connectionId/edit'
import { Route as AppAdminUsersUserIdRouteImport } from './routes/_app/admin/users/$userId'
import { Route as AppAdminTeamsTeamIdRouteImport } from './routes/_app/admin/teams/$teamId'
import { Route as AppVoiceExtensionsExtensionIdIndexRouteImport } from './routes/_app/voice/extensions/$extensionId/index'
import { Route as AppFaxNumbersFaxNumberIdIndexRouteImport } from './routes/_app/fax/numbers/$faxNumberId/index'
import { Route as AppFaxMessagesMessageIdIndexRouteImport } from './routes/_app/fax/messages/$messageId/index'
import { Route as AppVoiceExtensionsExtensionIdVoicemailRouteImport } from './routes/_app/voice/extensions/$extensionId/voicemail'
import { Route as AppVoiceExtensionsExtensionIdForwardingRouteImport } from './routes/_app/voice/extensions/$extensionId/forwarding'
import { Route as AppVoiceExtensionsExtensionIdEditRouteImport } from './routes/_app/voice/extensions/$extensionId/edit'
import { Route as AppVoiceExtensionsExtensionIdDndRouteImport } from './routes/_app/voice/extensions/$extensionId/dnd'
import { Route as AppFaxNumbersFaxNumberIdEditRouteImport } from './routes/_app/fax/numbers/$faxNumberId/edit'
import { Route as AppTeamsTeamIdInvitationsInvitationIdAcceptRouteImport } from './routes/_app/teams/$teamId/invitations/$invitationId/accept'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicVerifyEmailRoute = PublicVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMfaChallengeRoute = PublicMfaChallengeRouteImport.update({
  id: '/mfa-challenge',
  path: '/mfa-challenge',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLandingRoute = PublicLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceIndexRoute = AppVoiceIndexRouteImport.update({
  id: '/voice/',
  path: '/voice/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsIndexRoute = AppTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTeamsRoute,
} as any)
const AppTagsIndexRoute = AppTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportIndexRoute = AppSupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSupportRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationIndexRoute = AppOrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrganizationRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsIndexRoute = AppLocationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLocationsRoute,
} as any)
const AppGatewayIndexRoute = AppGatewayIndexRouteImport.update({
  id: '/gateway/',
  path: '/gateway/',
  getParentRoute: () => AppRoute,
} as any)
const AppFaxIndexRoute = AppFaxIndexRouteImport.update({
  id: '/fax/',
  path: '/fax/',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesIndexRoute = AppDevicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDevicesRoute,
} as any)
const AppConnectionsIndexRoute = AppConnectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConnectionsRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppVoicePhoneNumbersRoute = AppVoicePhoneNumbersRouteImport.update({
  id: '/voice/phone-numbers',
  path: '/voice/phone-numbers',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsNewRoute = AppTeamsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTeamsRoute,
} as any)
const AppTagsNewRoute = AppTagsNewRouteImport.update({
  id: '/tags/new',
  path: '/tags/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportNewRoute = AppSupportNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSupportRoute,
} as any)
const AppLocationsNewRoute = AppLocationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppLocationsRoute,
} as any)
const AppLocationsLocationIdRoute = AppLocationsLocationIdRouteImport.update({
  id: '/$locationId',
  path: '/$locationId',
  getParentRoute: () => AppLocationsRoute,
} as any)
const AppFaxSendRoute = AppFaxSendRouteImport.update({
  id: '/fax/send',
  path: '/fax/send',
  getParentRoute: () => AppRoute,
} as any)
const AppFaxEmailRoutesRoute = AppFaxEmailRoutesRouteImport.update({
  id: '/fax/email-routes',
  path: '/fax/email-routes',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesNewRoute = AppDevicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDevicesRoute,
} as any)
const AppConnectionsNewRoute = AppConnectionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppConnectionsRoute,
} as any)
const AppConnectionsConnectionIdRoute =
  AppConnectionsConnectionIdRouteImport.update({
    id: '/$connectionId',
    path: '/$connectionId',
    getParentRoute: () => AppConnectionsRoute,
  } as any)
const AppAdminVoiceRoute = AppAdminVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSystemRoute = AppAdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSupportRoute = AppAdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFaxRoute = AppAdminFaxRouteImport.update({
  id: '/fax',
  path: '/fax',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDevicesRoute = AppAdminDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppVoiceExtensionsIndexRoute = AppVoiceExtensionsIndexRouteImport.update({
  id: '/voice/extensions/',
  path: '/voice/extensions/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdIndexRoute = AppTeamsTeamIdIndexRouteImport.update({
  id: '/$teamId/',
  path: '/$teamId/',
  getParentRoute: () => AppTeamsRoute,
} as any)
const AppSupportTicketIdIndexRoute = AppSupportTicketIdIndexRouteImport.update({
  id: '/$ticketId/',
  path: '/$ticketId/',
  getParentRoute: () => AppSupportRoute,
} as any)
const AppLocationsLocationIdIndexRoute =
  AppLocationsLocationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppLocationsLocationIdRoute,
  } as any)
const AppFaxNumbersIndexRoute = AppFaxNumbersIndexRouteImport.update({
  id: '/fax/numbers/',
  path: '/fax/numbers/',
  getParentRoute: () => AppRoute,
} as any)
const AppFaxMessagesIndexRoute = AppFaxMessagesIndexRouteImport.update({
  id: '/fax/messages/',
  path: '/fax/messages/',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesDeviceIdIndexRoute = AppDevicesDeviceIdIndexRouteImport.update({
  id: '/$deviceId/',
  path: '/$deviceId/',
  getParentRoute: () => AppDevicesRoute,
} as any)
const AppConnectionsConnectionIdIndexRoute =
  AppConnectionsConnectionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppConnectionsConnectionIdRoute,
  } as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTeamsIndexRoute = AppAdminTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AppAdminRoute,
} as any)
const PublicAuthGoogleCallbackRoute =
  PublicAuthGoogleCallbackRouteImport.update({
    id: '/auth/google/callback',
    path: '/auth/google/callback',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAuthGithubCallbackRoute =
  PublicAuthGithubCallbackRouteImport.update({
    id: '/auth/github/callback',
    path: '/auth/github/callback',
    getParentRoute: () => PublicRoute,
  } as any)
const AppVoiceExtensionsNewRoute = AppVoiceExtensionsNewRouteImport.update({
  id: '/voice/extensions/new',
  path: '/voice/extensions/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTagsTagIdEditRoute = AppTagsTagIdEditRouteImport.update({
  id: '/tags/$tagId/edit',
  path: '/tags/$tagId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportTicketIdEditRoute = AppSupportTicketIdEditRouteImport.update({
  id: '/$ticketId/edit',
  path: '/$ticketId/edit',
  getParentRoute: () => AppSupportRoute,
} as any)
const AppFaxNumbersNewRoute = AppFaxNumbersNewRouteImport.update({
  id: '/fax/numbers/new',
  path: '/fax/numbers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesDeviceIdEditRoute = AppDevicesDeviceIdEditRouteImport.update({
  id: '/$deviceId/edit',
  path: '/$deviceId/edit',
  getParentRoute: () => AppDevicesRoute,
} as any)
const AppConnectionsConnectionIdEditRoute =
  AppConnectionsConnectionIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppConnectionsConnectionIdRoute,
  } as any)
const AppAdminUsersUserIdRoute = AppAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTeamsTeamIdRoute = AppAdminTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppVoiceExtensionsExtensionIdIndexRoute =
  AppVoiceExtensionsExtensionIdIndexRouteImport.update({
    id: '/voice/extensions/$extensionId/',
    path: '/voice/extensions/$extensionId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppFaxNumbersFaxNumberIdIndexRoute =
  AppFaxNumbersFaxNumberIdIndexRouteImport.update({
    id: '/fax/numbers/$faxNumberId/',
    path: '/fax/numbers/$faxNumberId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppFaxMessagesMessageIdIndexRoute =
  AppFaxMessagesMessageIdIndexRouteImport.update({
    id: '/fax/messages/$messageId/',
    path: '/fax/messages/$messageId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppVoiceExtensionsExtensionIdVoicemailRoute =
  AppVoiceExtensionsExtensionIdVoicemailRouteImport.update({
    id: '/voice/extensions/$extensionId/voicemail',
    path: '/voice/extensions/$extensionId/voicemail',
    getParentRoute: () => AppRoute,
  } as any)
const AppVoiceExtensionsExtensionIdForwardingRoute =
  AppVoiceExtensionsExtensionIdForwardingRouteImport.update({
    id: '/voice/extensions/$extensionId/forwarding',
    path: '/voice/extensions/$extensionId/forwarding',
    getParentRoute: () => AppRoute,
  } as any)
const AppVoiceExtensionsExtensionIdEditRoute =
  AppVoiceExtensionsExtensionIdEditRouteImport.update({
    id: '/voice/extensions/$extensionId/edit',
    path: '/voice/extensions/$extensionId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppVoiceExtensionsExtensionIdDndRoute =
  AppVoiceExtensionsExtensionIdDndRouteImport.update({
    id: '/voice/extensions/$extensionId/dnd',
    path: '/voice/extensions/$extensionId/dnd',
    getParentRoute: () => AppRoute,
  } as any)
const AppFaxNumbersFaxNumberIdEditRoute =
  AppFaxNumbersFaxNumberIdEditRouteImport.update({
    id: '/fax/numbers/$faxNumberId/edit',
    path: '/fax/numbers/$faxNumberId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppTeamsTeamIdInvitationsInvitationIdAcceptRoute =
  AppTeamsTeamIdInvitationsInvitationIdAcceptRouteImport.update({
    id: '/$teamId/invitations/$invitationId/accept',
    path: '/$teamId/invitations/$invitationId/accept',
    getParentRoute: () => AppTeamsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/connections': typeof AppConnectionsRouteWithChildren
  '/devices': typeof AppDevicesRouteWithChildren
  '/home': typeof AppHomeRoute
  '/locations': typeof AppLocationsRouteWithChildren
  '/organization': typeof AppOrganizationRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/support': typeof AppSupportRouteWithChildren
  '/teams': typeof AppTeamsRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/landing': typeof PublicLandingRoute
  '/login': typeof PublicLoginRoute
  '/mfa-challenge': typeof PublicMfaChallengeRoute
  '/privacy': typeof PublicPrivacyRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/signup': typeof PublicSignupRoute
  '/terms': typeof PublicTermsRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/devices': typeof AppAdminDevicesRoute
  '/admin/fax': typeof AppAdminFaxRoute
  '/admin/support': typeof AppAdminSupportRoute
  '/admin/system': typeof AppAdminSystemRoute
  '/admin/voice': typeof AppAdminVoiceRoute
  '/connections/$connectionId': typeof AppConnectionsConnectionIdRouteWithChildren
  '/connections/new': typeof AppConnectionsNewRoute
  '/devices/new': typeof AppDevicesNewRoute
  '/fax/email-routes': typeof AppFaxEmailRoutesRoute
  '/fax/send': typeof AppFaxSendRoute
  '/locations/$locationId': typeof AppLocationsLocationIdRouteWithChildren
  '/locations/new': typeof AppLocationsNewRoute
  '/support/new': typeof AppSupportNewRoute
  '/tags/new': typeof AppTagsNewRoute
  '/teams/new': typeof AppTeamsNewRoute
  '/voice/phone-numbers': typeof AppVoicePhoneNumbersRoute
  '/admin/': typeof AppAdminIndexRoute
  '/connections/': typeof AppConnectionsIndexRoute
  '/devices/': typeof AppDevicesIndexRoute
  '/fax/': typeof AppFaxIndexRoute
  '/gateway/': typeof AppGatewayIndexRoute
  '/locations/': typeof AppLocationsIndexRoute
  '/notifications/': typeof AppNotificationsIndexRoute
  '/organization/': typeof AppOrganizationIndexRoute
  '/profile/': typeof AppProfileIndexRoute
  '/support/': typeof AppSupportIndexRoute
  '/tags/': typeof AppTagsIndexRoute
  '/teams/': typeof AppTeamsIndexRoute
  '/voice/': typeof AppVoiceIndexRoute
  '/admin/teams/$teamId': typeof AppAdminTeamsTeamIdRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/connections/$connectionId/edit': typeof AppConnectionsConnectionIdEditRoute
  '/devices/$deviceId/edit': typeof AppDevicesDeviceIdEditRoute
  '/fax/numbers/new': typeof AppFaxNumbersNewRoute
  '/support/$ticketId/edit': typeof AppSupportTicketIdEditRoute
  '/tags/$tagId/edit': typeof AppTagsTagIdEditRoute
  '/voice/extensions/new': typeof AppVoiceExtensionsNewRoute
  '/auth/github/callback': typeof PublicAuthGithubCallbackRoute
  '/auth/google/callback': typeof PublicAuthGoogleCallbackRoute
  '/admin/teams/': typeof AppAdminTeamsIndexRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
  '/connections/$connectionId/': typeof AppConnectionsConnectionIdIndexRoute
  '/devices/$deviceId/': typeof AppDevicesDeviceIdIndexRoute
  '/fax/messages/': typeof AppFaxMessagesIndexRoute
  '/fax/numbers/': typeof AppFaxNumbersIndexRoute
  '/locations/$locationId/': typeof AppLocationsLocationIdIndexRoute
  '/support/$ticketId/': typeof AppSupportTicketIdIndexRoute
  '/teams/$teamId/': typeof AppTeamsTeamIdIndexRoute
  '/voice/extensions/': typeof AppVoiceExtensionsIndexRoute
  '/fax/numbers/$faxNumberId/edit': typeof AppFaxNumbersFaxNumberIdEditRoute
  '/voice/extensions/$extensionId/dnd': typeof AppVoiceExtensionsExtensionIdDndRoute
  '/voice/extensions/$extensionId/edit': typeof AppVoiceExtensionsExtensionIdEditRoute
  '/voice/extensions/$extensionId/forwarding': typeof AppVoiceExtensionsExtensionIdForwardingRoute
  '/voice/extensions/$extensionId/voicemail': typeof AppVoiceExtensionsExtensionIdVoicemailRoute
  '/fax/messages/$messageId/': typeof AppFaxMessagesMessageIdIndexRoute
  '/fax/numbers/$faxNumberId/': typeof AppFaxNumbersFaxNumberIdIndexRoute
  '/voice/extensions/$extensionId/': typeof AppVoiceExtensionsExtensionIdIndexRoute
  '/teams/$teamId/invitations/$invitationId/accept': typeof AppTeamsTeamIdInvitationsInvitationIdAcceptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/home': typeof AppHomeRoute
  '/settings': typeof AppSettingsRoute
  '/about': typeof PublicAboutRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/landing': typeof PublicLandingRoute
  '/login': typeof PublicLoginRoute
  '/mfa-challenge': typeof PublicMfaChallengeRoute
  '/privacy': typeof PublicPrivacyRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/signup': typeof PublicSignupRoute
  '/terms': typeof PublicTermsRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/devices': typeof AppAdminDevicesRoute
  '/admin/fax': typeof AppAdminFaxRoute
  '/admin/support': typeof AppAdminSupportRoute
  '/admin/system': typeof AppAdminSystemRoute
  '/admin/voice': typeof AppAdminVoiceRoute
  '/connections/new': typeof AppConnectionsNewRoute
  '/devices/new': typeof AppDevicesNewRoute
  '/fax/email-routes': typeof AppFaxEmailRoutesRoute
  '/fax/send': typeof AppFaxSendRoute
  '/locations/new': typeof AppLocationsNewRoute
  '/support/new': typeof AppSupportNewRoute
  '/tags/new': typeof AppTagsNewRoute
  '/teams/new': typeof AppTeamsNewRoute
  '/voice/phone-numbers': typeof AppVoicePhoneNumbersRoute
  '/admin': typeof AppAdminIndexRoute
  '/connections': typeof AppConnectionsIndexRoute
  '/devices': typeof AppDevicesIndexRoute
  '/fax': typeof AppFaxIndexRoute
  '/gateway': typeof AppGatewayIndexRoute
  '/locations': typeof AppLocationsIndexRoute
  '/notifications': typeof AppNotificationsIndexRoute
  '/organization': typeof AppOrganizationIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/support': typeof AppSupportIndexRoute
  '/tags': typeof AppTagsIndexRoute
  '/teams': typeof AppTeamsIndexRoute
  '/voice': typeof AppVoiceIndexRoute
  '/admin/teams/$teamId': typeof AppAdminTeamsTeamIdRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/connections/$connectionId/edit': typeof AppConnectionsConnectionIdEditRoute
  '/devices/$deviceId/edit': typeof AppDevicesDeviceIdEditRoute
  '/fax/numbers/new': typeof AppFaxNumbersNewRoute
  '/support/$ticketId/edit': typeof AppSupportTicketIdEditRoute
  '/tags/$tagId/edit': typeof AppTagsTagIdEditRoute
  '/voice/extensions/new': typeof AppVoiceExtensionsNewRoute
  '/auth/github/callback': typeof PublicAuthGithubCallbackRoute
  '/auth/google/callback': typeof PublicAuthGoogleCallbackRoute
  '/admin/teams': typeof AppAdminTeamsIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/connections/$connectionId': typeof AppConnectionsConnectionIdIndexRoute
  '/devices/$deviceId': typeof AppDevicesDeviceIdIndexRoute
  '/fax/messages': typeof AppFaxMessagesIndexRoute
  '/fax/numbers': typeof AppFaxNumbersIndexRoute
  '/locations/$locationId': typeof AppLocationsLocationIdIndexRoute
  '/support/$ticketId': typeof AppSupportTicketIdIndexRoute
  '/teams/$teamId': typeof AppTeamsTeamIdIndexRoute
  '/voice/extensions': typeof AppVoiceExtensionsIndexRoute
  '/fax/numbers/$faxNumberId/edit': typeof AppFaxNumbersFaxNumberIdEditRoute
  '/voice/extensions/$extensionId/dnd': typeof AppVoiceExtensionsExtensionIdDndRoute
  '/voice/extensions/$extensionId/edit': typeof AppVoiceExtensionsExtensionIdEditRoute
  '/voice/extensions/$extensionId/forwarding': typeof AppVoiceExtensionsExtensionIdForwardingRoute
  '/voice/extensions/$extensionId/voicemail': typeof AppVoiceExtensionsExtensionIdVoicemailRoute
  '/fax/messages/$messageId': typeof AppFaxMessagesMessageIdIndexRoute
  '/fax/numbers/$faxNumberId': typeof AppFaxNumbersFaxNumberIdIndexRoute
  '/voice/extensions/$extensionId': typeof AppVoiceExtensionsExtensionIdIndexRoute
  '/teams/$teamId/invitations/$invitationId/accept': typeof AppTeamsTeamIdInvitationsInvitationIdAcceptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/connections': typeof AppConnectionsRouteWithChildren
  '/_app/devices': typeof AppDevicesRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/locations': typeof AppLocationsRouteWithChildren
  '/_app/organization': typeof AppOrganizationRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/support': typeof AppSupportRouteWithChildren
  '/_app/teams': typeof AppTeamsRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/landing': typeof PublicLandingRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/mfa-challenge': typeof PublicMfaChallengeRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/verify-email': typeof PublicVerifyEmailRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/devices': typeof AppAdminDevicesRoute
  '/_app/admin/fax': typeof AppAdminFaxRoute
  '/_app/admin/support': typeof AppAdminSupportRoute
  '/_app/admin/system': typeof AppAdminSystemRoute
  '/_app/admin/voice': typeof AppAdminVoiceRoute
  '/_app/connections/$connectionId': typeof AppConnectionsConnectionIdRouteWithChildren
  '/_app/connections/new': typeof AppConnectionsNewRoute
  '/_app/devices/new': typeof AppDevicesNewRoute
  '/_app/fax/email-routes': typeof AppFaxEmailRoutesRoute
  '/_app/fax/send': typeof AppFaxSendRoute
  '/_app/locations/$locationId': typeof AppLocationsLocationIdRouteWithChildren
  '/_app/locations/new': typeof AppLocationsNewRoute
  '/_app/support/new': typeof AppSupportNewRoute
  '/_app/tags/new': typeof AppTagsNewRoute
  '/_app/teams/new': typeof AppTeamsNewRoute
  '/_app/voice/phone-numbers': typeof AppVoicePhoneNumbersRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/connections/': typeof AppConnectionsIndexRoute
  '/_app/devices/': typeof AppDevicesIndexRoute
  '/_app/fax/': typeof AppFaxIndexRoute
  '/_app/gateway/': typeof AppGatewayIndexRoute
  '/_app/locations/': typeof AppLocationsIndexRoute
  '/_app/notifications/': typeof AppNotificationsIndexRoute
  '/_app/organization/': typeof AppOrganizationIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/support/': typeof AppSupportIndexRoute
  '/_app/tags/': typeof AppTagsIndexRoute
  '/_app/teams/': typeof AppTeamsIndexRoute
  '/_app/voice/': typeof AppVoiceIndexRoute
  '/_app/admin/teams/$teamId': typeof AppAdminTeamsTeamIdRoute
  '/_app/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/_app/connections/$connectionId/edit': typeof AppConnectionsConnectionIdEditRoute
  '/_app/devices/$deviceId/edit': typeof AppDevicesDeviceIdEditRoute
  '/_app/fax/numbers/new': typeof AppFaxNumbersNewRoute
  '/_app/support/$ticketId/edit': typeof AppSupportTicketIdEditRoute
  '/_app/tags/$tagId/edit': typeof AppTagsTagIdEditRoute
  '/_app/voice/extensions/new': typeof AppVoiceExtensionsNewRoute
  '/_public/auth/github/callback': typeof PublicAuthGithubCallbackRoute
  '/_public/auth/google/callback': typeof PublicAuthGoogleCallbackRoute
  '/_app/admin/teams/': typeof AppAdminTeamsIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/connections/$connectionId/': typeof AppConnectionsConnectionIdIndexRoute
  '/_app/devices/$deviceId/': typeof AppDevicesDeviceIdIndexRoute
  '/_app/fax/messages/': typeof AppFaxMessagesIndexRoute
  '/_app/fax/numbers/': typeof AppFaxNumbersIndexRoute
  '/_app/locations/$locationId/': typeof AppLocationsLocationIdIndexRoute
  '/_app/support/$ticketId/': typeof AppSupportTicketIdIndexRoute
  '/_app/teams/$teamId/': typeof AppTeamsTeamIdIndexRoute
  '/_app/voice/extensions/': typeof AppVoiceExtensionsIndexRoute
  '/_app/fax/numbers/$faxNumberId/edit': typeof AppFaxNumbersFaxNumberIdEditRoute
  '/_app/voice/extensions/$extensionId/dnd': typeof AppVoiceExtensionsExtensionIdDndRoute
  '/_app/voice/extensions/$extensionId/edit': typeof AppVoiceExtensionsExtensionIdEditRoute
  '/_app/voice/extensions/$extensionId/forwarding': typeof AppVoiceExtensionsExtensionIdForwardingRoute
  '/_app/voice/extensions/$extensionId/voicemail': typeof AppVoiceExtensionsExtensionIdVoicemailRoute
  '/_app/fax/messages/$messageId/': typeof AppFaxMessagesMessageIdIndexRoute
  '/_app/fax/numbers/$faxNumberId/': typeof AppFaxNumbersFaxNumberIdIndexRoute
  '/_app/voice/extensions/$extensionId/': typeof AppVoiceExtensionsExtensionIdIndexRoute
  '/_app/teams/$teamId/invitations/$invitationId/accept': typeof AppTeamsTeamIdInvitationsInvitationIdAcceptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/connections'
    | '/devices'
    | '/home'
    | '/locations'
    | '/organization'
    | '/settings'
    | '/support'
    | '/teams'
    | '/about'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/mfa-challenge'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/audit'
    | '/admin/devices'
    | '/admin/fax'
    | '/admin/support'
    | '/admin/system'
    | '/admin/voice'
    | '/connections/$connectionId'
    | '/connections/new'
    | '/devices/new'
    | '/fax/email-routes'
    | '/fax/send'
    | '/locations/$locationId'
    | '/locations/new'
    | '/support/new'
    | '/tags/new'
    | '/teams/new'
    | '/voice/phone-numbers'
    | '/admin/'
    | '/connections/'
    | '/devices/'
    | '/fax/'
    | '/gateway/'
    | '/locations/'
    | '/notifications/'
    | '/organization/'
    | '/profile/'
    | '/support/'
    | '/tags/'
    | '/teams/'
    | '/voice/'
    | '/admin/teams/$teamId'
    | '/admin/users/$userId'
    | '/connections/$connectionId/edit'
    | '/devices/$deviceId/edit'
    | '/fax/numbers/new'
    | '/support/$ticketId/edit'
    | '/tags/$tagId/edit'
    | '/voice/extensions/new'
    | '/auth/github/callback'
    | '/auth/google/callback'
    | '/admin/teams/'
    | '/admin/users/'
    | '/connections/$connectionId/'
    | '/devices/$deviceId/'
    | '/fax/messages/'
    | '/fax/numbers/'
    | '/locations/$locationId/'
    | '/support/$ticketId/'
    | '/teams/$teamId/'
    | '/voice/extensions/'
    | '/fax/numbers/$faxNumberId/edit'
    | '/voice/extensions/$extensionId/dnd'
    | '/voice/extensions/$extensionId/edit'
    | '/voice/extensions/$extensionId/forwarding'
    | '/voice/extensions/$extensionId/voicemail'
    | '/fax/messages/$messageId/'
    | '/fax/numbers/$faxNumberId/'
    | '/voice/extensions/$extensionId/'
    | '/teams/$teamId/invitations/$invitationId/accept'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/home'
    | '/settings'
    | '/about'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/mfa-challenge'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/audit'
    | '/admin/devices'
    | '/admin/fax'
    | '/admin/support'
    | '/admin/system'
    | '/admin/voice'
    | '/connections/new'
    | '/devices/new'
    | '/fax/email-routes'
    | '/fax/send'
    | '/locations/new'
    | '/support/new'
    | '/tags/new'
    | '/teams/new'
    | '/voice/phone-numbers'
    | '/admin'
    | '/connections'
    | '/devices'
    | '/fax'
    | '/gateway'
    | '/locations'
    | '/notifications'
    | '/organization'
    | '/profile'
    | '/support'
    | '/tags'
    | '/teams'
    | '/voice'
    | '/admin/teams/$teamId'
    | '/admin/users/$userId'
    | '/connections/$connectionId/edit'
    | '/devices/$deviceId/edit'
    | '/fax/numbers/new'
    | '/support/$ticketId/edit'
    | '/tags/$tagId/edit'
    | '/voice/extensions/new'
    | '/auth/github/callback'
    | '/auth/google/callback'
    | '/admin/teams'
    | '/admin/users'
    | '/connections/$connectionId'
    | '/devices/$deviceId'
    | '/fax/messages'
    | '/fax/numbers'
    | '/locations/$locationId'
    | '/support/$ticketId'
    | '/teams/$teamId'
    | '/voice/extensions'
    | '/fax/numbers/$faxNumberId/edit'
    | '/voice/extensions/$extensionId/dnd'
    | '/voice/extensions/$extensionId/edit'
    | '/voice/extensions/$extensionId/forwarding'
    | '/voice/extensions/$extensionId/voicemail'
    | '/fax/messages/$messageId'
    | '/fax/numbers/$faxNumberId'
    | '/voice/extensions/$extensionId'
    | '/teams/$teamId/invitations/$invitationId/accept'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_app'
    | '/_public'
    | '/_app/admin'
    | '/_app/connections'
    | '/_app/devices'
    | '/_app/home'
    | '/_app/locations'
    | '/_app/organization'
    | '/_app/settings'
    | '/_app/support'
    | '/_app/teams'
    | '/_public/about'
    | '/_public/forgot-password'
    | '/_public/landing'
    | '/_public/login'
    | '/_public/mfa-challenge'
    | '/_public/privacy'
    | '/_public/reset-password'
    | '/_public/signup'
    | '/_public/terms'
    | '/_public/verify-email'
    | '/_app/admin/audit'
    | '/_app/admin/devices'
    | '/_app/admin/fax'
    | '/_app/admin/support'
    | '/_app/admin/system'
    | '/_app/admin/voice'
    | '/_app/connections/$connectionId'
    | '/_app/connections/new'
    | '/_app/devices/new'
    | '/_app/fax/email-routes'
    | '/_app/fax/send'
    | '/_app/locations/$locationId'
    | '/_app/locations/new'
    | '/_app/support/new'
    | '/_app/tags/new'
    | '/_app/teams/new'
    | '/_app/voice/phone-numbers'
    | '/_app/admin/'
    | '/_app/connections/'
    | '/_app/devices/'
    | '/_app/fax/'
    | '/_app/gateway/'
    | '/_app/locations/'
    | '/_app/notifications/'
    | '/_app/organization/'
    | '/_app/profile/'
    | '/_app/support/'
    | '/_app/tags/'
    | '/_app/teams/'
    | '/_app/voice/'
    | '/_app/admin/teams/$teamId'
    | '/_app/admin/users/$userId'
    | '/_app/connections/$connectionId/edit'
    | '/_app/devices/$deviceId/edit'
    | '/_app/fax/numbers/new'
    | '/_app/support/$ticketId/edit'
    | '/_app/tags/$tagId/edit'
    | '/_app/voice/extensions/new'
    | '/_public/auth/github/callback'
    | '/_public/auth/google/callback'
    | '/_app/admin/teams/'
    | '/_app/admin/users/'
    | '/_app/connections/$connectionId/'
    | '/_app/devices/$deviceId/'
    | '/_app/fax/messages/'
    | '/_app/fax/numbers/'
    | '/_app/locations/$locationId/'
    | '/_app/support/$ticketId/'
    | '/_app/teams/$teamId/'
    | '/_app/voice/extensions/'
    | '/_app/fax/numbers/$faxNumberId/edit'
    | '/_app/voice/extensions/$extensionId/dnd'
    | '/_app/voice/extensions/$extensionId/edit'
    | '/_app/voice/extensions/$extensionId/forwarding'
    | '/_app/voice/extensions/$extensionId/voicemail'
    | '/_app/fax/messages/$messageId/'
    | '/_app/fax/numbers/$faxNumberId/'
    | '/_app/voice/extensions/$extensionId/'
    | '/_app/teams/$teamId/invitations/$invitationId/accept'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/verify-email': {
      id: '/_public/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicVerifyEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/mfa-challenge': {
      id: '/_public/mfa-challenge'
      path: '/mfa-challenge'
      fullPath: '/mfa-challenge'
      preLoaderRoute: typeof PublicMfaChallengeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/landing': {
      id: '/_public/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof PublicLandingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization': {
      id: '/_app/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations': {
      id: '/_app/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections': {
      id: '/_app/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voice/': {
      id: '/_app/voice/'
      path: '/voice'
      fullPath: '/voice/'
      preLoaderRoute: typeof AppVoiceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/': {
      id: '/_app/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof AppTeamsIndexRouteImport
      parentRoute: typeof AppTeamsRoute
    }
    '/_app/tags/': {
      id: '/_app/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof AppTagsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/': {
      id: '/_app/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof AppSupportIndexRouteImport
      parentRoute: typeof AppSupportRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization/': {
      id: '/_app/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof AppOrganizationIndexRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/notifications/': {
      id: '/_app/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations/': {
      id: '/_app/locations/'
      path: '/'
      fullPath: '/locations/'
      preLoaderRoute: typeof AppLocationsIndexRouteImport
      parentRoute: typeof AppLocationsRoute
    }
    '/_app/gateway/': {
      id: '/_app/gateway/'
      path: '/gateway'
      fullPath: '/gateway/'
      preLoaderRoute: typeof AppGatewayIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fax/': {
      id: '/_app/fax/'
      path: '/fax'
      fullPath: '/fax/'
      preLoaderRoute: typeof AppFaxIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices/': {
      id: '/_app/devices/'
      path: '/'
      fullPath: '/devices/'
      preLoaderRoute: typeof AppDevicesIndexRouteImport
      parentRoute: typeof AppDevicesRoute
    }
    '/_app/connections/': {
      id: '/_app/connections/'
      path: '/'
      fullPath: '/connections/'
      preLoaderRoute: typeof AppConnectionsIndexRouteImport
      parentRoute: typeof AppConnectionsRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/voice/phone-numbers': {
      id: '/_app/voice/phone-numbers'
      path: '/voice/phone-numbers'
      fullPath: '/voice/phone-numbers'
      preLoaderRoute: typeof AppVoicePhoneNumbersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/new': {
      id: '/_app/teams/new'
      path: '/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof AppTeamsNewRouteImport
      parentRoute: typeof AppTeamsRoute
    }
    '/_app/tags/new': {
      id: '/_app/tags/new'
      path: '/tags/new'
      fullPath: '/tags/new'
      preLoaderRoute: typeof AppTagsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/new': {
      id: '/_app/support/new'
      path: '/new'
      fullPath: '/support/new'
      preLoaderRoute: typeof AppSupportNewRouteImport
      parentRoute: typeof AppSupportRoute
    }
    '/_app/locations/new': {
      id: '/_app/locations/new'
      path: '/new'
      fullPath: '/locations/new'
      preLoaderRoute: typeof AppLocationsNewRouteImport
      parentRoute: typeof AppLocationsRoute
    }
    '/_app/locations/$locationId': {
      id: '/_app/locations/$locationId'
      path: '/$locationId'
      fullPath: '/locations/$locationId'
      preLoaderRoute: typeof AppLocationsLocationIdRouteImport
      parentRoute: typeof AppLocationsRoute
    }
    '/_app/fax/send': {
      id: '/_app/fax/send'
      path: '/fax/send'
      fullPath: '/fax/send'
      preLoaderRoute: typeof AppFaxSendRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fax/email-routes': {
      id: '/_app/fax/email-routes'
      path: '/fax/email-routes'
      fullPath: '/fax/email-routes'
      preLoaderRoute: typeof AppFaxEmailRoutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices/new': {
      id: '/_app/devices/new'
      path: '/new'
      fullPath: '/devices/new'
      preLoaderRoute: typeof AppDevicesNewRouteImport
      parentRoute: typeof AppDevicesRoute
    }
    '/_app/connections/new': {
      id: '/_app/connections/new'
      path: '/new'
      fullPath: '/connections/new'
      preLoaderRoute: typeof AppConnectionsNewRouteImport
      parentRoute: typeof AppConnectionsRoute
    }
    '/_app/connections/$connectionId': {
      id: '/_app/connections/$connectionId'
      path: '/$connectionId'
      fullPath: '/connections/$connectionId'
      preLoaderRoute: typeof AppConnectionsConnectionIdRouteImport
      parentRoute: typeof AppConnectionsRoute
    }
    '/_app/admin/voice': {
      id: '/_app/admin/voice'
      path: '/voice'
      fullPath: '/admin/voice'
      preLoaderRoute: typeof AppAdminVoiceRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/system': {
      id: '/_app/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AppAdminSystemRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/support': {
      id: '/_app/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AppAdminSupportRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/fax': {
      id: '/_app/admin/fax'
      path: '/fax'
      fullPath: '/admin/fax'
      preLoaderRoute: typeof AppAdminFaxRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/devices': {
      id: '/_app/admin/devices'
      path: '/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AppAdminDevicesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/voice/extensions/': {
      id: '/_app/voice/extensions/'
      path: '/voice/extensions'
      fullPath: '/voice/extensions/'
      preLoaderRoute: typeof AppVoiceExtensionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId/': {
      id: '/_app/teams/$teamId/'
      path: '/$teamId'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof AppTeamsTeamIdIndexRouteImport
      parentRoute: typeof AppTeamsRoute
    }
    '/_app/support/$ticketId/': {
      id: '/_app/support/$ticketId/'
      path: '/$ticketId'
      fullPath: '/support/$ticketId/'
      preLoaderRoute: typeof AppSupportTicketIdIndexRouteImport
      parentRoute: typeof AppSupportRoute
    }
    '/_app/locations/$locationId/': {
      id: '/_app/locations/$locationId/'
      path: '/'
      fullPath: '/locations/$locationId/'
      preLoaderRoute: typeof AppLocationsLocationIdIndexRouteImport
      parentRoute: typeof AppLocationsLocationIdRoute
    }
    '/_app/fax/numbers/': {
      id: '/_app/fax/numbers/'
      path: '/fax/numbers'
      fullPath: '/fax/numbers/'
      preLoaderRoute: typeof AppFaxNumbersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fax/messages/': {
      id: '/_app/fax/messages/'
      path: '/fax/messages'
      fullPath: '/fax/messages/'
      preLoaderRoute: typeof AppFaxMessagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices/$deviceId/': {
      id: '/_app/devices/$deviceId/'
      path: '/$deviceId'
      fullPath: '/devices/$deviceId/'
      preLoaderRoute: typeof AppDevicesDeviceIdIndexRouteImport
      parentRoute: typeof AppDevicesRoute
    }
    '/_app/connections/$connectionId/': {
      id: '/_app/connections/$connectionId/'
      path: '/'
      fullPath: '/connections/$connectionId/'
      preLoaderRoute: typeof AppConnectionsConnectionIdIndexRouteImport
      parentRoute: typeof AppConnectionsConnectionIdRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/teams/': {
      id: '/_app/admin/teams/'
      path: '/teams'
      fullPath: '/admin/teams/'
      preLoaderRoute: typeof AppAdminTeamsIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_public/auth/google/callback': {
      id: '/_public/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof PublicAuthGoogleCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/github/callback': {
      id: '/_public/auth/github/callback'
      path: '/auth/github/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof PublicAuthGithubCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/voice/extensions/new': {
      id: '/_app/voice/extensions/new'
      path: '/voice/extensions/new'
      fullPath: '/voice/extensions/new'
      preLoaderRoute: typeof AppVoiceExtensionsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tags/$tagId/edit': {
      id: '/_app/tags/$tagId/edit'
      path: '/tags/$tagId/edit'
      fullPath: '/tags/$tagId/edit'
      preLoaderRoute: typeof AppTagsTagIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/$ticketId/edit': {
      id: '/_app/support/$ticketId/edit'
      path: '/$ticketId/edit'
      fullPath: '/support/$ticketId/edit'
      preLoaderRoute: typeof AppSupportTicketIdEditRouteImport
      parentRoute: typeof AppSupportRoute
    }
    '/_app/fax/numbers/new': {
      id: '/_app/fax/numbers/new'
      path: '/fax/numbers/new'
      fullPath: '/fax/numbers/new'
      preLoaderRoute: typeof AppFaxNumbersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices/$deviceId/edit': {
      id: '/_app/devices/$deviceId/edit'
      path: '/$deviceId/edit'
      fullPath: '/devices/$deviceId/edit'
      preLoaderRoute: typeof AppDevicesDeviceIdEditRouteImport
      parentRoute: typeof AppDevicesRoute
    }
    '/_app/connections/$connectionId/edit': {
      id: '/_app/connections/$connectionId/edit'
      path: '/edit'
      fullPath: '/connections/$connectionId/edit'
      preLoaderRoute: typeof AppConnectionsConnectionIdEditRouteImport
      parentRoute: typeof AppConnectionsConnectionIdRoute
    }
    '/_app/admin/users/$userId': {
      id: '/_app/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AppAdminUsersUserIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/teams/$teamId': {
      id: '/_app/admin/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/admin/teams/$teamId'
      preLoaderRoute: typeof AppAdminTeamsTeamIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/voice/extensions/$extensionId/': {
      id: '/_app/voice/extensions/$extensionId/'
      path: '/voice/extensions/$extensionId'
      fullPath: '/voice/extensions/$extensionId/'
      preLoaderRoute: typeof AppVoiceExtensionsExtensionIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fax/numbers/$faxNumberId/': {
      id: '/_app/fax/numbers/$faxNumberId/'
      path: '/fax/numbers/$faxNumberId'
      fullPath: '/fax/numbers/$faxNumberId/'
      preLoaderRoute: typeof AppFaxNumbersFaxNumberIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fax/messages/$messageId/': {
      id: '/_app/fax/messages/$messageId/'
      path: '/fax/messages/$messageId'
      fullPath: '/fax/messages/$messageId/'
      preLoaderRoute: typeof AppFaxMessagesMessageIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voice/extensions/$extensionId/voicemail': {
      id: '/_app/voice/extensions/$extensionId/voicemail'
      path: '/voice/extensions/$extensionId/voicemail'
      fullPath: '/voice/extensions/$extensionId/voicemail'
      preLoaderRoute: typeof AppVoiceExtensionsExtensionIdVoicemailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voice/extensions/$extensionId/forwarding': {
      id: '/_app/voice/extensions/$extensionId/forwarding'
      path: '/voice/extensions/$extensionId/forwarding'
      fullPath: '/voice/extensions/$extensionId/forwarding'
      preLoaderRoute: typeof AppVoiceExtensionsExtensionIdForwardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voice/extensions/$extensionId/edit': {
      id: '/_app/voice/extensions/$extensionId/edit'
      path: '/voice/extensions/$extensionId/edit'
      fullPath: '/voice/extensions/$extensionId/edit'
      preLoaderRoute: typeof AppVoiceExtensionsExtensionIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voice/extensions/$extensionId/dnd': {
      id: '/_app/voice/extensions/$extensionId/dnd'
      path: '/voice/extensions/$extensionId/dnd'
      fullPath: '/voice/extensions/$extensionId/dnd'
      preLoaderRoute: typeof AppVoiceExtensionsExtensionIdDndRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fax/numbers/$faxNumberId/edit': {
      id: '/_app/fax/numbers/$faxNumberId/edit'
      path: '/fax/numbers/$faxNumberId/edit'
      fullPath: '/fax/numbers/$faxNumberId/edit'
      preLoaderRoute: typeof AppFaxNumbersFaxNumberIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId/invitations/$invitationId/accept': {
      id: '/_app/teams/$teamId/invitations/$invitationId/accept'
      path: '/$teamId/invitations/$invitationId/accept'
      fullPath: '/teams/$teamId/invitations/$invitationId/accept'
      preLoaderRoute: typeof AppTeamsTeamIdInvitationsInvitationIdAcceptRouteImport
      parentRoute: typeof AppTeamsRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminDevicesRoute: typeof AppAdminDevicesRoute
  AppAdminFaxRoute: typeof AppAdminFaxRoute
  AppAdminSupportRoute: typeof AppAdminSupportRoute
  AppAdminSystemRoute: typeof AppAdminSystemRoute
  AppAdminVoiceRoute: typeof AppAdminVoiceRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminTeamsTeamIdRoute: typeof AppAdminTeamsTeamIdRoute
  AppAdminUsersUserIdRoute: typeof AppAdminUsersUserIdRoute
  AppAdminTeamsIndexRoute: typeof AppAdminTeamsIndexRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminDevicesRoute: AppAdminDevicesRoute,
  AppAdminFaxRoute: AppAdminFaxRoute,
  AppAdminSupportRoute: AppAdminSupportRoute,
  AppAdminSystemRoute: AppAdminSystemRoute,
  AppAdminVoiceRoute: AppAdminVoiceRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminTeamsTeamIdRoute: AppAdminTeamsTeamIdRoute,
  AppAdminUsersUserIdRoute: AppAdminUsersUserIdRoute,
  AppAdminTeamsIndexRoute: AppAdminTeamsIndexRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppConnectionsConnectionIdRouteChildren {
  AppConnectionsConnectionIdEditRoute: typeof AppConnectionsConnectionIdEditRoute
  AppConnectionsConnectionIdIndexRoute: typeof AppConnectionsConnectionIdIndexRoute
}

const AppConnectionsConnectionIdRouteChildren: AppConnectionsConnectionIdRouteChildren =
  {
    AppConnectionsConnectionIdEditRoute: AppConnectionsConnectionIdEditRoute,
    AppConnectionsConnectionIdIndexRoute: AppConnectionsConnectionIdIndexRoute,
  }

const AppConnectionsConnectionIdRouteWithChildren =
  AppConnectionsConnectionIdRoute._addFileChildren(
    AppConnectionsConnectionIdRouteChildren,
  )

interface AppConnectionsRouteChildren {
  AppConnectionsConnectionIdRoute: typeof AppConnectionsConnectionIdRouteWithChildren
  AppConnectionsNewRoute: typeof AppConnectionsNewRoute
  AppConnectionsIndexRoute: typeof AppConnectionsIndexRoute
}

const AppConnectionsRouteChildren: AppConnectionsRouteChildren = {
  AppConnectionsConnectionIdRoute: AppConnectionsConnectionIdRouteWithChildren,
  AppConnectionsNewRoute: AppConnectionsNewRoute,
  AppConnectionsIndexRoute: AppConnectionsIndexRoute,
}

const AppConnectionsRouteWithChildren = AppConnectionsRoute._addFileChildren(
  AppConnectionsRouteChildren,
)

interface AppDevicesRouteChildren {
  AppDevicesNewRoute: typeof AppDevicesNewRoute
  AppDevicesIndexRoute: typeof AppDevicesIndexRoute
  AppDevicesDeviceIdEditRoute: typeof AppDevicesDeviceIdEditRoute
  AppDevicesDeviceIdIndexRoute: typeof AppDevicesDeviceIdIndexRoute
}

const AppDevicesRouteChildren: AppDevicesRouteChildren = {
  AppDevicesNewRoute: AppDevicesNewRoute,
  AppDevicesIndexRoute: AppDevicesIndexRoute,
  AppDevicesDeviceIdEditRoute: AppDevicesDeviceIdEditRoute,
  AppDevicesDeviceIdIndexRoute: AppDevicesDeviceIdIndexRoute,
}

const AppDevicesRouteWithChildren = AppDevicesRoute._addFileChildren(
  AppDevicesRouteChildren,
)

interface AppLocationsLocationIdRouteChildren {
  AppLocationsLocationIdIndexRoute: typeof AppLocationsLocationIdIndexRoute
}

const AppLocationsLocationIdRouteChildren: AppLocationsLocationIdRouteChildren =
  {
    AppLocationsLocationIdIndexRoute: AppLocationsLocationIdIndexRoute,
  }

const AppLocationsLocationIdRouteWithChildren =
  AppLocationsLocationIdRoute._addFileChildren(
    AppLocationsLocationIdRouteChildren,
  )

interface AppLocationsRouteChildren {
  AppLocationsLocationIdRoute: typeof AppLocationsLocationIdRouteWithChildren
  AppLocationsNewRoute: typeof AppLocationsNewRoute
  AppLocationsIndexRoute: typeof AppLocationsIndexRoute
}

const AppLocationsRouteChildren: AppLocationsRouteChildren = {
  AppLocationsLocationIdRoute: AppLocationsLocationIdRouteWithChildren,
  AppLocationsNewRoute: AppLocationsNewRoute,
  AppLocationsIndexRoute: AppLocationsIndexRoute,
}

const AppLocationsRouteWithChildren = AppLocationsRoute._addFileChildren(
  AppLocationsRouteChildren,
)

interface AppOrganizationRouteChildren {
  AppOrganizationIndexRoute: typeof AppOrganizationIndexRoute
}

const AppOrganizationRouteChildren: AppOrganizationRouteChildren = {
  AppOrganizationIndexRoute: AppOrganizationIndexRoute,
}

const AppOrganizationRouteWithChildren = AppOrganizationRoute._addFileChildren(
  AppOrganizationRouteChildren,
)

interface AppSupportRouteChildren {
  AppSupportNewRoute: typeof AppSupportNewRoute
  AppSupportIndexRoute: typeof AppSupportIndexRoute
  AppSupportTicketIdEditRoute: typeof AppSupportTicketIdEditRoute
  AppSupportTicketIdIndexRoute: typeof AppSupportTicketIdIndexRoute
}

const AppSupportRouteChildren: AppSupportRouteChildren = {
  AppSupportNewRoute: AppSupportNewRoute,
  AppSupportIndexRoute: AppSupportIndexRoute,
  AppSupportTicketIdEditRoute: AppSupportTicketIdEditRoute,
  AppSupportTicketIdIndexRoute: AppSupportTicketIdIndexRoute,
}

const AppSupportRouteWithChildren = AppSupportRoute._addFileChildren(
  AppSupportRouteChildren,
)

interface AppTeamsRouteChildren {
  AppTeamsNewRoute: typeof AppTeamsNewRoute
  AppTeamsIndexRoute: typeof AppTeamsIndexRoute
  AppTeamsTeamIdIndexRoute: typeof AppTeamsTeamIdIndexRoute
  AppTeamsTeamIdInvitationsInvitationIdAcceptRoute: typeof AppTeamsTeamIdInvitationsInvitationIdAcceptRoute
}

const AppTeamsRouteChildren: AppTeamsRouteChildren = {
  AppTeamsNewRoute: AppTeamsNewRoute,
  AppTeamsIndexRoute: AppTeamsIndexRoute,
  AppTeamsTeamIdIndexRoute: AppTeamsTeamIdIndexRoute,
  AppTeamsTeamIdInvitationsInvitationIdAcceptRoute:
    AppTeamsTeamIdInvitationsInvitationIdAcceptRoute,
}

const AppTeamsRouteWithChildren = AppTeamsRoute._addFileChildren(
  AppTeamsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppConnectionsRoute: typeof AppConnectionsRouteWithChildren
  AppDevicesRoute: typeof AppDevicesRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppLocationsRoute: typeof AppLocationsRouteWithChildren
  AppOrganizationRoute: typeof AppOrganizationRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRouteWithChildren
  AppTeamsRoute: typeof AppTeamsRouteWithChildren
  AppFaxEmailRoutesRoute: typeof AppFaxEmailRoutesRoute
  AppFaxSendRoute: typeof AppFaxSendRoute
  AppTagsNewRoute: typeof AppTagsNewRoute
  AppVoicePhoneNumbersRoute: typeof AppVoicePhoneNumbersRoute
  AppFaxIndexRoute: typeof AppFaxIndexRoute
  AppGatewayIndexRoute: typeof AppGatewayIndexRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppTagsIndexRoute: typeof AppTagsIndexRoute
  AppVoiceIndexRoute: typeof AppVoiceIndexRoute
  AppFaxNumbersNewRoute: typeof AppFaxNumbersNewRoute
  AppTagsTagIdEditRoute: typeof AppTagsTagIdEditRoute
  AppVoiceExtensionsNewRoute: typeof AppVoiceExtensionsNewRoute
  AppFaxMessagesIndexRoute: typeof AppFaxMessagesIndexRoute
  AppFaxNumbersIndexRoute: typeof AppFaxNumbersIndexRoute
  AppVoiceExtensionsIndexRoute: typeof AppVoiceExtensionsIndexRoute
  AppFaxNumbersFaxNumberIdEditRoute: typeof AppFaxNumbersFaxNumberIdEditRoute
  AppVoiceExtensionsExtensionIdDndRoute: typeof AppVoiceExtensionsExtensionIdDndRoute
  AppVoiceExtensionsExtensionIdEditRoute: typeof AppVoiceExtensionsExtensionIdEditRoute
  AppVoiceExtensionsExtensionIdForwardingRoute: typeof AppVoiceExtensionsExtensionIdForwardingRoute
  AppVoiceExtensionsExtensionIdVoicemailRoute: typeof AppVoiceExtensionsExtensionIdVoicemailRoute
  AppFaxMessagesMessageIdIndexRoute: typeof AppFaxMessagesMessageIdIndexRoute
  AppFaxNumbersFaxNumberIdIndexRoute: typeof AppFaxNumbersFaxNumberIdIndexRoute
  AppVoiceExtensionsExtensionIdIndexRoute: typeof AppVoiceExtensionsExtensionIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppConnectionsRoute: AppConnectionsRouteWithChildren,
  AppDevicesRoute: AppDevicesRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppLocationsRoute: AppLocationsRouteWithChildren,
  AppOrganizationRoute: AppOrganizationRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRouteWithChildren,
  AppTeamsRoute: AppTeamsRouteWithChildren,
  AppFaxEmailRoutesRoute: AppFaxEmailRoutesRoute,
  AppFaxSendRoute: AppFaxSendRoute,
  AppTagsNewRoute: AppTagsNewRoute,
  AppVoicePhoneNumbersRoute: AppVoicePhoneNumbersRoute,
  AppFaxIndexRoute: AppFaxIndexRoute,
  AppGatewayIndexRoute: AppGatewayIndexRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppTagsIndexRoute: AppTagsIndexRoute,
  AppVoiceIndexRoute: AppVoiceIndexRoute,
  AppFaxNumbersNewRoute: AppFaxNumbersNewRoute,
  AppTagsTagIdEditRoute: AppTagsTagIdEditRoute,
  AppVoiceExtensionsNewRoute: AppVoiceExtensionsNewRoute,
  AppFaxMessagesIndexRoute: AppFaxMessagesIndexRoute,
  AppFaxNumbersIndexRoute: AppFaxNumbersIndexRoute,
  AppVoiceExtensionsIndexRoute: AppVoiceExtensionsIndexRoute,
  AppFaxNumbersFaxNumberIdEditRoute: AppFaxNumbersFaxNumberIdEditRoute,
  AppVoiceExtensionsExtensionIdDndRoute: AppVoiceExtensionsExtensionIdDndRoute,
  AppVoiceExtensionsExtensionIdEditRoute:
    AppVoiceExtensionsExtensionIdEditRoute,
  AppVoiceExtensionsExtensionIdForwardingRoute:
    AppVoiceExtensionsExtensionIdForwardingRoute,
  AppVoiceExtensionsExtensionIdVoicemailRoute:
    AppVoiceExtensionsExtensionIdVoicemailRoute,
  AppFaxMessagesMessageIdIndexRoute: AppFaxMessagesMessageIdIndexRoute,
  AppFaxNumbersFaxNumberIdIndexRoute: AppFaxNumbersFaxNumberIdIndexRoute,
  AppVoiceExtensionsExtensionIdIndexRoute:
    AppVoiceExtensionsExtensionIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLandingRoute: typeof PublicLandingRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicMfaChallengeRoute: typeof PublicMfaChallengeRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicSignupRoute: typeof PublicSignupRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicVerifyEmailRoute: typeof PublicVerifyEmailRoute
  PublicAuthGithubCallbackRoute: typeof PublicAuthGithubCallbackRoute
  PublicAuthGoogleCallbackRoute: typeof PublicAuthGoogleCallbackRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLandingRoute: PublicLandingRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicMfaChallengeRoute: PublicMfaChallengeRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicSignupRoute: PublicSignupRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicVerifyEmailRoute: PublicVerifyEmailRoute,
  PublicAuthGithubCallbackRoute: PublicAuthGithubCallbackRoute,
  PublicAuthGoogleCallbackRoute: PublicAuthGoogleCallbackRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
