"""Domain modules for the application."""

from app.domain import (
    accounts,
    admin,
    analytics,
    attachments,
    call_routing,
    connections,
    devices,
    e911,
    events,
    fax,
    gateway,
    locations,
    notifications,
    organizations,
    phone_numbers,
    schedules,
    support,
    system,
    tags,
    tasks,
    teams,
    voice,
    voicemail,
    webhooks,
)

__all__ = (
    "accounts",
    "admin",
    "analytics",
    "attachments",
    "call_routing",
    "connections",
    "devices",
    "e911",
    "events",
    "fax",
    "gateway",
    "locations",
    "notifications",
    "organizations",
    "phone_numbers",
    "schedules",
    "support",
    "system",
    "tags",
    "tasks",
    "teams",
    "voice",
    "voicemail",
    "webhooks",
)
